### ISSUE TITLE
Saying "no" to enabling MacAddressSpoofing still enables it

### ISSUE THREAD

**Issue by theodthompson** [Microsoft/Virtualization-Documentation#105]
"Mac address spoofing isn't enabled, nested guests won't have network!"
"Would you like to enable? (Y/N)"
N
... still enables MacAddressSpoofing

**Comment by scooley** [comment]
@mebersol for heads up

**Comment by scooley** [comment]
Ping @theodthompson @mebersol.

Re-sending issues as people get back from the holidays.

**Comment by scooley** [comment]
@theodthompson I think a fix was merged in, correct?
