### ISSUE TITLE
 No Command  `Install-ContainerHost.ps1` on Windows 10 build 10586 

### ISSUE THREAD

**Issue by qin-nz** [Microsoft/Virtualization-Documentation#106]
On my  Windows 10 build 10586 , “Get-ContainerImage” is not exist.
So `Install-ContainerHost.ps1` failed.
https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/inplace_setup.md

**Comment by qin-nz** [comment]
My Windows 10 is Professional Edition

**Comment by neilpeterson** [comment]
Qin-nz, you will need to use Hyper-V on Windows 10 for the container host. This doc details a scripted deployment, which will work on Windows 10 - https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/container_setup .

Let me know if this resolves our issue.

Thanks

neilp

**Comment by qin-nz** [comment]
Is it means my `Windows 10` need a `Windows Server 2016` Virtual Machine, and run docker on `Windows Server 2016` ?

**Comment by neilpeterson** [comment]
Yes this is correct. The container role can only be enabled on a Windows Server 2016 TP4 installation.

**Comment by scooley** [comment]
Closing this issue -- good feedback but not a bug.

**Comment by neilpeterson** [comment]
I've updated the doc's to be more clear around this topic.
