### ISSUE TITLE
Managing IIS in a container

### ISSUE THREAD

**Issue by cwoolum** [Microsoft/Virtualization-Documentation#120]
Hi All, 

Adding IIS to a container makes sense but can anyone explain the intended model for how sites should be deployed using IIS? 

1. Should it be 1 site per container?
2. Can IIS only be managed visit command line?
3. Are we limited to .Net Core or can we deploy apps built on the full .net framework?

Any guidance would be awesome!

**Comment by Aoqidx** [comment]
Hi cwoolum
  How do you add IIS to a container successfully? I deploied a Windows Container Host to a phycial system(with Windows Server 2016 TP4). When install IIS in a container with the command 'Install-WindowsFeature web-server', the console stuck at 'Collecting Data 3%' and then never moved.
  Now,I wanna try again on a Hyper-V VM, the step saving Container OS Image form OneGet always timed out. Is there a link for me to download the Container OS Image?

**Comment by rbinrais** [comment]
Cwoolum -  For #2 you can use "appcmd.exe" [c:\windows\system32\inetsrv] to manage the iis from command line.

**Comment by neilpeterson** [comment]
Assuming this is resolved with the advice given above, can re-open is necessary,
