### ISSUE TITLE
Trying to install Hyper-V containers and getting the following errors PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage ServerDatacenterCore -Hyperv c:\New-ContainerHost.ps1 : File C:\New-ContainerHost.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170. At line:1 char:1 + c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage Serve ... + ~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : SecurityError: (:) [], PSSecurityException     + FullyQualifiedErrorId : UnauthorizedAccess

### ISSUE THREAD

**Issue by mohajibrahim** [Microsoft/Virtualization-Documentation#128]
Trying to install Hyper-V containers and getting the following errors PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage ServerDatacenterCore -Hyperv c:\New-ContainerHost.ps1 : File C:\New-ContainerHost.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170. At line:1 char:1 + c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage Serve ... + ~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : SecurityError: (:) [], PSSecurityException     + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by mohajibrahim** [comment]
<<RESOLVED>> I resolved this issue by updating my PowerShell Execution policy security to unrestricted on my machine, however you can update the scope for process or session only...

PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage ServerDatacenterCore -Hyperv
c:\New-ContainerHost.ps1 : File C:\New-ContainerHost.ps1 cannot be loaded. The file C:\New-ContainerHost.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage Serve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\WINDOWS\system32> PowerShell.exe -ExecutionPolicy
Cannot process the execution policy because of a missing policy name. A policy name must follow -ExecutionPolicy.

PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
    [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
    [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
    [-WindowStyle <style>] [-EncodedCommand <Base64EncodedCommand>]
    [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
    [-Command { - | <script-block> [-args <arg-array>]
                  | <string> [<CommandParameters>] } ]

PowerShell[.exe] -Help | -? | /?

-PSConsoleFile
    Loads the specified Windows PowerShell console file. To create a console
    file, use Export-Console in Windows PowerShell.

-Version
    Starts the specified version of Windows PowerShell.
    Enter a version number with the parameter, such as "-version 2.0".

-NoLogo
    Hides the copyright banner at startup.

-NoExit
    Does not exit after running startup commands.

-Sta
    Starts the shell using a single-threaded apartment.
    Single-threaded apartment (STA) is the default.

-Mta
    Start the shell using a multithreaded apartment.

-NoProfile
    Does not load the Windows PowerShell profile.

-NonInteractive
    Does not present an interactive prompt to the user.

-InputFormat
    Describes the format of data sent to Windows PowerShell. Valid values are
    "Text" (text strings) or "XML" (serialized CLIXML format).

-OutputFormat
    Determines how output from Windows PowerShell is formatted. Valid values
    are "Text" (text strings) or "XML" (serialized CLIXML format).

-WindowStyle
    Sets the window style to Normal, Minimized, Maximized or Hidden.

-EncodedCommand
    Accepts a base-64-encoded string version of a command. Use this parameter
    to submit commands to Windows PowerShell that require complex quotation
    marks or curly braces.

-File
    Runs the specified script in the local scope ("dot-sourced"), so that the
    functions and variables that the script creates are available in the
    current session. Enter the script file path and any parameters.
    File must be the last parameter in the command, because all characters
    typed after the File parameter name are interpreted
    as the script file path followed by the script parameters.

-ExecutionPolicy
    Sets the default execution policy for the current session and saves it
    in the $env:PSExecutionPolicyPreference environment variable.
    This parameter does not change the Windows PowerShell execution policy
    that is set in the registry.

-Command
    Executes the specified commands (and any parameters) as though they were
    typed at the Windows PowerShell command prompt, and then exits, unless
    NoExit is specified. The value of Command can be "-", a string. or a
    script block.

    If the value of Command is "-", the command text is read from standard
    input.

    If the value of Command is a script block, the script block must be enclosed
    in braces ({}). You can specify a script block only when running PowerShell.exe
    in Windows PowerShell. The results of the script block are returned to the
    parent shell as deserialized XML objects, not live objects.

    If the value of Command is a string, Command must be the last parameter
    in the command , because any characters typed after the command are
    interpreted as the command arguments.

    To write a string that runs a Windows PowerShell command, use the format:
        "& {<command>}"
    where the quotation marks indicate a string and the invoke operator (&)
    causes the command to be executed.

-Help, -?, /?
    Shows this message. If you are typing a PowerShell.exe command in Windows
    PowerShell, prepend the command parameters with a hyphen (-), not a forward
    slash (/). You can use either a hyphen or forward slash in Cmd.exe.

EXAMPLES
    PowerShell -PSConsoleFile SqlSnapIn.Psc1
    PowerShell -version 2.0 -NoLogo -InputFormat text -OutputFormat XML
    PowerShell -Command {Get-EventLog -LogName security}
    PowerShell -Command "& {Get-EventLog -LogName security}"

    # To use the -EncodedCommand parameter:
    $command = 'dir "c:\program files" '
    $bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
    $encodedCommand = [Convert]::ToBase64String($bytes)
    powershell.exe -encodedCommand $encodedCommand
PS C:\WINDOWS\system32> Get-ExecutionPolicy -Scope CurrentUser
Undefined
PS C:\WINDOWS\system32> Set-ExecutionPolicy -ExecutionPolicy Bypass
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy -ExecutionPolicy Bypass
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
PS C:\WINDOWS\system32> Get-ExecutionPolicy -Scope CurrentUser
Undefined
PS C:\WINDOWS\system32> Set-ExecutionPolicy -ExecutionPolicy Unrestricted
Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting is overridden by
a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective
execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more
information please see "Get-Help Set-ExecutionPolicy".
At line:1 char:1
+ Set-ExecutionPolicy -ExecutionPolicy Unrestricted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
PS C:\WINDOWS\system32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       AllSigned
  CurrentUser       Undefined
 LocalMachine    Unrestricted


PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage ServerDatacenterCore -Hyperv
c:\New-ContainerHost.ps1 : File C:\New-ContainerHost.ps1 cannot be loaded. The file C:\New-ContainerHost.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage Serve ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\WINDOWS\system32> Get-ExecutionPolicy
AllSigned
PS C:\WINDOWS\system32> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted
PS C:\WINDOWS\system32> Get-ExecutionPolicy
Unrestricted
<<For Security reasons of my 64-bit Machine, Please note I will change my ExecutionPolicy back to Undefined or Restricted after installing my CONTAINER in HYPER-V below>>
PS C:\WINDOWS\system32>

<<RESOLVED>>
Now I can start installing my Container in Hyper-V as seen below ... 

PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer1 -WindowsImage ServerDatacenterCore -Hyperv

cmdlet New-ContainerHost.ps1 at command pipeline position 1
Supply values for the following parameters:
Password: *********
Before installing and using the Windows Server Technical Preview 4 with Containers virtual machine you must:
    1. Review the license terms by navigating to this link: http://aka.ms/tp4/containerseula
    2. Print and retain a copy of the license terms for your records.
By downloading and using the Windows Server Technical Preview 4 with Containers virtual machine you agree to such
license terms. Please confirm you have accepted and agree to the license terms.
[N] No  [Y] Yes  [?] Help (default is "N"): Y
Using VHD path C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
Using external switch External VM Virtual Switch
Copying ServerDatacenterCore ISO from https://aka.ms/tp4/serveriso to C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\WindowsServerTP4.iso (this may take several minutes)...

I will then continue adding my APP in my new Container and as the new image and upload it to my private Repository.

**Comment by scooley** [comment]
Thanks for the heads up -- we'll cleanup the docs to remove that confusion
