### ISSUE TITLE
 Trying to Start Hyper-V container and getting the following error after has been created ...    (X) The application encountered an error while attempting to change the state of 'HyperVContainer2'. 	'HyperVContainer2' failed to start. 	'HyperVContainer2' could not initialize. 	'HyperVContainer2' failed to start. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0) 	'HyperVContainer2' could not initialize. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0) 

### ISSUE THREAD

**Issue by mohajibrahim** [Microsoft/Virtualization-Documentation#129]
Trying to Start Hyper-V container and getting the following error after has been created ...
   (X) The application encountered an error while attempting to change the state of 'HyperVContainer2'.
	'HyperVContainer2' failed to start.
	'HyperVContainer2' could not initialize.
	'HyperVContainer2' failed to start. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0)
	'HyperVContainer2' could not initialize. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0)

PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainer2 -WindowsImage ServerDatacenterCore -Hyperv

cmdlet New-ContainerHost.ps1 at command pipeline position 1
Supply values for the following parameters:
Password: *********
Before installing and using the Windows Server Technical Preview 4 with Containers virtual machine you must:
    1. Review the license terms by navigating to this link: http://aka.ms/tp4/containerseula
    2. Print and retain a copy of the license terms for your records.
By downloading and using the Windows Server Technical Preview 4 with Containers virtual machine you agree to such license terms. Please confirm you have accepted and agree to
the license terms.
[N] No  [Y] Yes  [?] Help (default is "N"): Y
Using VHD path C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
Using external switch External VM Virtual Switch
The latest ServerDatacenterCore VHD is already present on this system.
ServerDatacenterCore Container OS Image (WIM) is already present on this system.
Creating VHD files for VM HyperVContainer2...
VHD mount must be synchronized with other running instances of this script.  Waiting for exclusive access...
Mounting ServerDatacenterCore VHD for offline processing...
Enabling Containers feature on drive E...
Enabling Hyper-V feature on drive E...
Copying Docker into ServerDatacenterCore VHD...
Copying NSSM into ServerDatacenterCore VHD...
This script uses a third party tool: NSSM. For more information, see https://nssm.cc/usage
Downloading NSSM...
Extracting NSSM from archive...
ExpandArchiveHelper : Failed to create file 'C:\Users\admin\AppData\Local\Temp\nssm\nssm-2.24\win32\nssm.exe' while expanding the archive file
'C:\Users\admin\AppData\Local\Temp\nssm-2.24.zip' contents as the file 'C:\Users\admin\AppData\Local\Temp\nssm\nssm-2.24\win32\nssm.exe' already exists. Use the -Force
parameter if you want to overwrite the existing directory 'C:\Users\admin\AppData\Local\Temp\nssm\nssm-2.24\win32\nssm.exe' contents when expanding the archive file.
At C:\windows\system32\windowspowershell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:394 char:17
+ ...             ExpandArchiveHelper $resolvedSourcePaths $resolvedDestina ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (C:\Users\admin\...\win32\nssm.exe:String) [Write-Error], IOException
    + FullyQualifiedErrorId : ExpandArchiveFileExists,ExpandArchiveHelper

Writing default unattend.xml...
Copying Install-ContainerHost.ps1 into ServerDatacenterCore VHD...
Dismounting VHD...
Creating VM HyperVContainer2...
Configuring VM HyperVContainer2...
Connecting VM to switch External VM Virtual Switch
WARNING: Nested virtualization is an unsupported preview feature. Hypervisors other than the Hyper-V hypervisor running in a guest virtual machine are likely to fail.
Furthermore, some Hyper-V features are incompatible with nested virtualization, such as dynamic memory, checkpoints, and save/restore.
Starting VM HyperVContainer2...
Start-VM : 'HyperVContainer2' failed to start.
Not enough memory in the system to start the virtual machine HyperVContainer2.
Could not initialize memory: Ran out of memory (0x8007000E).
'HyperVContainer2' failed to start. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0)
Not enough memory in the system to start the virtual machine HyperVContainer2 with ram size 1024 megabytes. (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0)
'HyperVContainer2' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID DC2D005A-197B-4E20-8B4B-E5E444266AE0)
At C:\New-ContainerHost.ps1:787 char:9
+         $vm | Start-VM | Out-Null
+               ~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

Waiting for VM HyperVContainer2 to boot...

Actions taken:
-------------------
 1) - Upgraded Memory from 1024MB to 2048MB for the container in Hper-V Settings.
 2) - Deleted all temp files in folder C:\Users\admin\AppData\Local\Temp
 3) - Re-Attached VHD on E: drive in Disk Management using C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\HyperVContainer2-WIM.vhdx
 4) Deleted previous attempts of unsuccessful and incomplete containers such as the "Mylittleservercontainer", "HyperVcontainer1" in Hyper-V.

<< RESOLVED >>

PS C:\WINDOWS\system32> c:\New-ContainerHost.ps1 -VmName HyperVContainerfirst -WindowsImage ServerDatacenterCore -Hyperv

cmdlet New-ContainerHost.ps1 at command pipeline position 1
Supply values for the following parameters:
Password: *********
Before installing and using the Windows Server Technical Preview 4 with Containers virtual machine you must:
    1. Review the license terms by navigating to this link: http://aka.ms/tp4/containerseula
    2. Print and retain a copy of the license terms for your records.
By downloading and using the Windows Server Technical Preview 4 with Containers virtual machine you agree to such license terms. Please confirm you have accepted and agree to the license terms.
[N] No  [Y] Yes  [?] Help (default is "N"): Y
Using VHD path C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
Using external switch External VM Virtual Switch
The latest ServerDatacenterCore VHD is already present on this system.
ServerDatacenterCore Container OS Image (WIM) is already present on this system.
Creating VHD files for VM HyperVContainerfirst...
VHD mount must be synchronized with other running instances of this script.  Waiting for exclusive access...
Mounting ServerDatacenterCore VHD for offline processing...
Enabling Containers feature on drive E...
Enabling Hyper-V feature on drive E...
Copying Docker into ServerDatacenterCore VHD...
Copying NSSM into ServerDatacenterCore VHD...
This script uses a third party tool: NSSM. For more information, see https://nssm.cc/usage
Downloading NSSM...
Extracting NSSM from archive...
Writing default unattend.xml...
Copying Install-ContainerHost.ps1 into ServerDatacenterCore VHD...
Dismounting VHD...
Creating VM HyperVContainerfirst...
Configuring VM HyperVContainerfirst...
Connecting VM to switch External VM Virtual Switch
WARNING: Nested virtualization is an unsupported preview feature. Hypervisors other than the Hyper-V hypervisor running in a guest virtual machine are likely to fail. Furthermore, some Hyper-V
features are incompatible with nested virtualization, such as dynamic memory, checkpoints, and save/restore.
Starting VM HyperVContainerfirst...
Waiting for VM HyperVContainerfirst to boot...
Connected to VM HyperVContainerfirst Heartbeat IC.
Waiting for specialization to complete (this may take a few minutes)...
C:\New-ContainerHost.ps1 : Could not connect to PS Direct after 30 minutes
At line:1 char:1
+ c:\New-ContainerHost.ps1 -VmName HyperVContainerfirst -WindowsImage S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ContainerHost.ps1

PS C:\WINDOWS\system32>

<<<<<<<<  Timedout because I went for a hour Lunch, I went back to Hyper-V and started HyperVContainerfirst container and it asked me for the Password which I entered. I was able to successfully login and see the container by listing the Windows files and Directory >>>>>>>>>>>>>
>>>>>>>>> I will continue with installing Application in my container

**Comment by mohajibrahim** [comment]
See the Actions taken and << RESOLVED >> sections in the comments box above for the solutions.

**Comment by ardentm** [comment]
Hello, let me kindly ask you few things. 
I don't understand the third part < (3) - Re-Attached VHD on E: drive in Disk Management using C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\HyperVContainer2-WIM.vhdx> 
What is HyperVContainer2-WIM.vhdx file and where can I find it? And why a lot of steps are needed to run hyper-v container?

**Comment by mohajibrahim** [comment]
@ardentm , VHD is the Virtual Hard Disk you create yourself in Hyper-V. When your container gets created in Hyper-V then right-click on it and go to Settings and add your VHD in either IDE or SCSI Controller. If you have a windows container and not Hper-V then your VHD in Windows Disk Management utility (hopefully you have a desktop GUI with your flavor of Windows 2016) otherwise you will need to use PowerShell commands to add the VHD.
