### ISSUE TITLE
Setting up Containers without Internet Connectivity

### ISSUE THREAD

**Issue by planet** [Microsoft/Virtualization-Documentation#131]
Does anyone know a method to install and configure containers on Windows 2016 TP4 without Internet  connectivity?  I've gotten as far as installing docker but don't know how to pull down the docker images manually.  Any insight would be appreciated.

This what I see basically

```ps
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
Querying status of Windows feature: Hyper-V...
Feature Hyper-V is already enabled.
Waiting for Hyper-V Management...
Networking is already configured.  Confirming configuration...
Getting Container OS image (WindowsServerCore) version 10.0.10586.0 from OneGet (this may take a few minutes)...
Install-ContainerImage : Unable to download.
At C:\Scripts\Install-ContainerHost.ps1:461 char:17
+ ...              Install-ContainerImage $imageName -Version $imageVersion
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-ContainerImage

Container base image install complete.  Querying container images...
Waiting for VMMS to return image at (02/04/2016 06:08:16)...
Waiting for VMMS to return image at (02/04/2016 06:08:18)...
Waiting for VMMS to return image at (02/04/2016 06:08:20)...
Waiting for VMMS to return image at (02/04/2016 06:08:22)...
Waiting for VMMS to return image at (02/04/2016 06:08:24)...
Waiting for VMMS to return image at (02/04/2016 06:08:26)...
Waiting for VMMS to return image at (02/04/2016 06:08:28)...
Waiting for VMMS to return image at (02/04/2016 06:08:30)...
Waiting for VMMS to return image at (02/04/2016 06:08:32)...
Waiting for VMMS to return image at (02/04/2016 06:08:34)...
```

and it never grabs the image..  Is there a manual work around?  Download files on another box and copy to the server?

**Comment by planet** [comment]
I am using the `Install-ContainerHost.ps1` script by the way. @mebersol @StefanScherer

**Comment by mebersol** [comment]
Looks like there is a bug in Install-ContainerHost.ps1 - we should throw if the download fails.

@planet - you can use Save-ContainerImage to copy down the container base image to a .wim on another machine, and then copy it to the container host and use Install-ContainerOsImage to install this image as a container base package.

**Comment by scooley** [comment]
@neilpeterson -- we should answer this somewhere.  Maybe FAQ or as an inline note?

**Comment by neilpeterson** [comment]
@scooley - agreed, Ill get it in.

**Comment by StefanScherer** [comment]
@planet Haven't tried it yet, but perhaps with `Install-ContainerHost.ps1 -WimPath ...` as mentioned here: [Install-ContianerHost.ps1#L49-L50](https://github.com/Microsoft/Virtualization-Documentation/blob/89562a58c51efb14738cbaa7c629f229a4814606/windows-server-container-tools/Install-ContainerHost/Install-ContainerHost.ps1#L49-L50)

**Comment by planet** [comment]
> @planet Haven't tried it yet, but perhaps with Install-ContainerHost.ps1 -WimPath ... as mentioned here: Install-ContianerHost.ps1#L49-L50

I will try and get back to you.

**Comment by planet** [comment]
Resolved my issue.  It turned out to be a certificate related issue on my end.  Thanks everyone.
