### ISSUE TITLE
publish this repo as PDF or ebook

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#132]
This can be done instantly via 
https://www.gitbook.com/
Please have a look.
 
additional help and readings:
https://github.com/GitbookIO/gitbook
http://help.gitbook.com/
alternatively:
https://github.com/alanshaw/markdown-pdf

**Comment by scooley** [comment]
Thanks for the heads up :)

**Comment by rs38** [comment]
closed and forgotten???
