### ISSUE TITLE
Convert-WindowsImage not handling arrays for Edition

### ISSUE THREAD

**Issue by janssenjones** [Microsoft/Virtualization-Documentation#136]
When passing a string to Convert-WindowsImage, it works: 
Convert-WindowsImage -Edition "ServerDataCenter"

When passing an array to Convert-WindowsImage, it errors:
Convert-WindowsImage -Edition @("ServerDataCenter","ServerDataCenterCore")
ERROR : The property 'Count' cannot be found on this object. Verify that the property exists.

**Comment by neilpeterson** [comment]
Assuming this has been resolved with TP5 revision. Will re-open if necessary.
