### ISSUE TITLE
PDF bookmarks with Hypervisor Top-Level Functional Specification

### ISSUE THREAD

**Issue by jrmwng** [Microsoft/Virtualization-Documentation#141]
Please spare time in adding PDF bookmarks to your specifications. Thanks!

**Comment by theodthompson** [comment]
@jrmwng does it work if you download the spec? (right-click "raw", save target as)

**Comment by jrmwng** [comment]
I can download those PDF files of the specs to my local folder, but those PDF files do not contains bookmarks (table of contents).

**Comment by theodthompson** [comment]
I'm sorry this isn't working for you... what PDF reader are you using?

**Comment by jrmwng** [comment]
adobe pdf reader touch. bookmarks are available in most pdf files (manuals) I read.

**Comment by rvka** [comment]
I wonder why this issue has been closed by a totally unrelated commit?

The problem is still there: none of the tlfs documents has bookmarks.
