### ISSUE TITLE
work_in_progress.md not up2date with shared folders

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#146]
shared folders came with tp4 and are already part of the documentation, so that part in here needs updates:
Virtualization-Documentation / virtualization / windowscontainers / about / work_in_progress.md 

> `All non-C:/ drives are visible in containers
> 
> All non-C:/ drives available to the container host are automatically mapped into new running Windows Containers.
> 
> At this point in time there is no way to selectively map folders into a container, as an interim work around drives are mapped automatically.
> 
> *Work Around: *
>  We're working on it. In the future there will be folder sharing.
> `

**Comment by neilpeterson** [comment]
Thanks for the catch - I will get the docs updated.

**Comment by neilpeterson** [comment]
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/work_in_progress

**Comment by rs38** [comment]
only curious: why does that edit not occur in github history? Or did I miss it?

**Comment by neilpeterson** [comment]
We have a private and public repo which are kept in sync, however there is a delay in this sync action. The history will eventually merge up. The published docs themselves are built from the private repo.

**Comment by rs38** [comment]
thank you for explaining!
