### ISSUE TITLE
fix for docker.exe tp4

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#148]
Insert an early hint in the quick start to this link below that docker.exe needs an update in azure as well as locally.
https://raw.githubusercontent.com/Microsoft/Virtualization-Documentation/live/windows-server-container-tools/Update-ContainerHost/Update-ContainerHost.ps1

**Comment by neilpeterson** [comment]
I've added this to the Azure doc. I believe the installations scripts should handle this in local installs. I will follow up on this.

Thanks.
