### ISSUE TITLE
Install-ContainerHost.ps1 broken -> if ($HyperV -or Test-Nano) Unexpected token

### ISSUE THREAD

**Issue by StefanScherer** [Microsoft/Virtualization-Documentation#149]
The commit https://github.com/Microsoft/Virtualization-Documentation/commit/61175c8c735120cfc3b3de4826090dfda9257793 seems to break the installation.

I now get this error:

<img width="809" alt="bildschirmfoto 2016-02-29 um 16 13 46" src="https://cloud.githubusercontent.com/assets/207759/13398650/8cab8342-deff-11e5-9ed4-1f2a53e2a8d8.png">

if ($HyperV -or Test-Nano)
Unexpected token 'Test-Nano' in expression or statement.
At C:\Install-ContainerHost.ps1:446 char:25

**Comment by scooley** [comment]
Should work now.

**Comment by StefanScherer** [comment]
LGTM :-) 
Thank you!
