### ISSUE TITLE
New-ContainerHost.ps1 may fail when temp directory path elements are too long

### ISSUE THREAD

**Issue by hill0826** [Microsoft/Virtualization-Documentation#160]
When temp directory path elements are too long, the `Get-Nsmm` function within `New-ContainerHost.ps1` obtains a path using one or more short names which causes the `Remove-Item` command to fail.

[Related issue on ServerFault](http://serverfault.com/questions/527381/powershell-remove-item-cant-handle-junctions/530409)

We was able to workaround this issue by making the adjustment on line 1080 as mentioned in the accepted ServerFault answer:
`- $nssmZip = "$($env:temp)\$(Split-Path $nssmUri -Leaf)"`
`+ $nssmZip = [System.IO.Path]::GetFullPath("$($env:temp)\$(Split-Path $nssmUri -Leaf)")`

This is the error encountered when paths were long enough for short names to be used:
```powershell
C:\New-ContainerHost.ps1 : An object at the specified path C:\Users\FILE~1.NAM does not exist.
At line:1 char:1
+ C:\New-ContainerHost.ps1 -VMName docker-hyperv -WindowsImage ServerD ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ContainerHost.ps1
```

**Comment by neilpeterson** [comment]
Assuming this has been resolved with TP5 revision. Will re-open if necessary.
