### ISSUE TITLE
"Community Resources for Hyper-V and Windows Containers" link 404s

### ISSUE THREAD

**Issue by theodthompson** [Microsoft/Virtualization-Documentation#163]
https://msdn.microsoft.com/en-us/virtualization/community/community_overview.md

**Comment by scooley** [comment]
https://msdn.microsoft.com/en-us/virtualization/community/community_overview ;).  It works if you delete the .md at the end.

**Comment by theodthompson** [comment]
sorry should have been more specific... the link is broken from this page
https://msdn.microsoft.com/virtualization/hyperv_on_windows/windows_welcome

I'll fix it

**Comment by theodthompson** [comment]
fixed
