### ISSUE TITLE
de-dupe element ids for better anchor links

### ISSUE THREAD

**Issue by friism** [Microsoft/Virtualization-Documentation#177]
Take this page: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview#windows-containers

It has two elements with `id` attribute value of `windows-containers`. That means that I cannot generate and anchor-link to the second element, like this: `https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview#windows-containers`

**Comment by neilpeterson** [comment]
Thanks Michael - this looks like an issue with how the Markdown conversion is interpreting the ID. I will fix it up in this doc and then spot check the remaining for identical issues.

neilp

**Comment by neilpeterson** [comment]
This has been completed.
