### ISSUE TITLE
Sample dockerfiles not doing what their corresponding README.md say

### ISSUE THREAD

**Issue by mathiasconradt** [Microsoft/Virtualization-Documentation#179]
The documentation on
https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-samples/mysql

says:

> This dockerfile will **install** MySQL Community Server, version 5.7.9, in a Windows Server Core based container.

but all the [dockerfile](https://github.com/Microsoft/Virtualization-Documentation/blob/master/windows-server-container-samples/mysql/dockerfile) does it setting the PATH, it's not executing any setup. Or am I missing something?

`RUN setx /M PATH "%PATH%;C:\mysql-5.7.9-winx64"`

Same goes for the Sqlite example but maybe others as well.

**Comment by neilpeterson** [comment]
I have begun to update the dockerfile samples, both mysql and sqlite included.

mysql - https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-container-samples/windowsservercore/mysql
sqlite - https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-container-samples/windowsservercore/sqlite

**Comment by neilpeterson** [comment]
Closing this out as a majority of these have been updated.
