### ISSUE TITLE
connect to Azure VM with WinRM

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#182]
I just checked the docs at  
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/azure_setup
and I get in trouble to find the right endpoint settings in Azure.
It seeems that the concept has completly changed with Azure classic and new RM.
Currently I have a Win2006 TP4 VM running and cannot even find any "endpoints".

My goal is to reach my VM and container inside via WinRM from  a corporate network through proxy.
not an easy one right now?!

**Comment by mathiasconradt** [comment]
@rs38 Just a note: I found an issue with host port binding yesterday, which I had described here: http://superuser.com/questions/1057223/windows-container-port-binding-on-windows-server-2016-not-working/1057894, which seems to be a regression of Win2016 TP4 (as opposed to TP3).
Not sure if your issue is related, but maybe, since it's also related to port opening to the public. (I'm not using Azure but on-premise server).

**Comment by neilpeterson** [comment]
rs38, there are two different virtual machine types or deployment models in Azure, Classic and Resource Manager. This doc was written using the classic model, and is still valid when deploying a classic virtual machine.

If using resource manager, you are correct, the endpoint concept has changed somewhat. The new artifact for allowing traffic in is a Network Security Group. When creating the virtual machine, a Network Security Group should have been created, and can be modified with allowed inbound and outbound ports.

https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-nsg/

We have a work item for the next release to re-work this doc.

Thanks

neilp

**Comment by rs38** [comment]
this is really strange: I created a fresh Azure core tp4 and nano both with selecting "classic" from the dropbox and now I can remote on these boxes with WinRM over proxy as expected. Is this an issue or misunderstaning?   
when I have some time, I will try from scratch, unless TP5 appears soon

**Comment by neilpeterson** [comment]
This is expected, the default configuration for a classic virtual machine is that port 3389 and 5986 are configured on the endpoint.

![ep](https://cloud.githubusercontent.com/assets/7844635/14150171/a0f86d82-f65c-11e5-868b-1c94e7e541ed.jpg)

To compare, a virtual machine deployed into a resource group has default network security group that includes only port 3389.

![nsg](https://cloud.githubusercontent.com/assets/7844635/14150207/ccf0d85c-f65c-11e5-8a4f-ed7268607430.jpg)

Both an endpoint and nsg can be configured after deployment, so ports can be added.

neilp

**Comment by rs38** [comment]
of course I added these WinRM Ports in the inbound rules, but without success.
I try to reproduce if time is left.

**Comment by neilpeterson** [comment]
For reference, this template may help - https://github.com/Azure/azure-quickstart-templates/tree/master/windows-server-containers-preview .
