### ISSUE TITLE
Hyper-V nested virtualization on Root OS

### ISSUE THREAD

**Issue by lewisl9029** [Microsoft/Virtualization-Documentation#184]
Now that nested virtualization is supported for Hyper-V VMs, I was wondering if it'd also be possible to enable it for the Root OS. 

This would be very useful for running other virtualization products like VirtualBox and VMware Workstation in the Root OS under Hyper-V (the other way around, Hyper-V nested under VMware Workstation, has been possible for quite some time). 

Right now when I try to run a 64-bit VMware Workstation VM under the Hyper-V Root OS (with the `vmx.allowNested = TRUE` flag), I get the following error:

```
This virtual machine is configured for 64-bit guest operating systems. However, 64-bit operation is not possible.

This host does not support Intel VT-x.

For more detailed information, see http://vmware.com/info?id=152.
```

**Comment by lewisl9029** [comment]
Ideally, both. =)
I use Vagrant for most of my dev work and a vast majority of the Vagrant boxes on [Atlas](https://atlas.hashicorp.com/boxes/search) were built for VirtualBox and Workstation, with only a handful of popular distro's available for Hyper-V.

**Comment by theodthompson** [comment]
Good to know. Thanks! 
Just curious - what are you using Hyper-V in this situation?

**Comment by lewisl9029** [comment]
I was trying out the new Docker for Windows Beta, which integrates with Hyper-V: https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

My experiences with the beta have been pretty great so far, but it'd be nice to not have to choose between the new Docker + Hyper-V integration and Vagrant + VirtualBox/Workstation.

**Comment by theodthompson** [comment]
Got it. Thanks for your feedback... closing this for now.

**Comment by matthiasg** [comment]
is this even on microsoft's radar ? or not deemed important ?

**Comment by theodthompson** [comment]
@matthiasg definitely on the radar :)

**Comment by flydvorkin** [comment]
New Hyper-V from Windows Server 2019 (17763.1) has the same problem. No way to enable nested virtualization for Root Os

**Comment by kwinz** [comment]
https://windowsserver.uservoice.com/forums/295050-virtualization/suggestions/39471682-allow-host-to-run-other-hypervisor-via-nested-vir
74 👍 so far
