### ISSUE TITLE
Install-ContainerHost.ps1 - The ampersand character not allowed

### ISSUE THREAD

**Issue by naeemsarfraz** [Microsoft/Virtualization-Documentation#205]
Just created a new container host and getting this error

![container setup error](https://cloud.githubusercontent.com/assets/1143865/14603055/7fff427a-0563-11e6-8b18-6daf1c48d886.PNG)

I can run the command Install-ContainerHost.ps1 myself (having picked it out of the unattend.xml). What is the issue?

I've deleted the unattend.xml and restarted the server however the command is still attempting to run each time I login.

**Comment by naeemsarfraz** [comment]
I used `Disable-ScheduledTask ConatinerBoostrap` to disable the task and that's stopped it from running. I'm still keen to stop the initial error, am I doing something wrong?

**Comment by PatrickLang** [comment]
That script shouldn't be needed anymore. The new installation steps don't set or require a scheduled task. I'll close this out
