### ISSUE TITLE
cmd command not recognized by windowsservercore image

### ISSUE THREAD

**Issue by arun-gupta** [Microsoft/Virtualization-Documentation#216]
Running `docker run --name iisbase -it windowsservercore cmd` in Windows Server TP5 clears up the console and gives the error:

    The parameter is incorrect

The exact error is shown here:

<img width="1016" alt="screen shot 2016-04-28 at 6 30 31 pm" src="https://cloud.githubusercontent.com/assets/113947/14906373/8572be26-0d6f-11e6-84f7-f82c52568216.png">

**Comment by neilpeterson** [comment]
Arun - I've run this across two systems and cannot reproduce the issue. Can you tell me more about your system, how was it built?

**Comment by neilpeterson** [comment]
I just found your blog, set up looks good. 

@enderb-ms, @taylorb-microsoft  - have you seen this issue? I cannot repo.

**Comment by arun-gupta** [comment]
More details about my setup: http://blog.couchbase.com/2016/april/windows-server-2016-virtualbox-docker and http://blog.couchbase.com/2016/april/setup-docker-windows-server-2016

**Comment by StefanScherer** [comment]
I have tried `docker run --name iisbase -it windowsservercore cmd` in an administrator powershell and it worked in my setup. 

(But exiting from that container takes 60 seconds (type exit in that cmd shell in the container and run `docker ps` on the server in a second powershell). I have to investigate that and will file an issue in docker/docker repo)

**Comment by jhowardmsft** [comment]
Known. There's a workaround documented but can't find the link from my phone. On the msdn forum. Is a sticky near the top

**Comment by neilpeterson** [comment]
https://social.msdn.microsoft.com/Forums/en-US/e2751260-4494-4b60-999e-5ea27ccbe1db/workaround-to-increase-boot-time-for-windows-server-core-containers?forum=windowscontainers

**Comment by arun-gupta** [comment]
I tried that a few times yesterday and got the same error. But it seems to be behaving well this morning!

Will reopen the bug if I see it again.

FWIW, I'm seeing the slowness as experienced by @StefanScherer

**Comment by StefanScherer** [comment]
@arun-gupta Just apply the patch script from the forum link above. This solved my problem. Trying to add this to my packer box for now.
