### ISSUE TITLE
useing a number for edition fails with string conversion

### ISSUE THREAD

**Issue by BladeFireLight** [Microsoft/Virtualization-Documentation#22]
I know this is an issue on Windows 10. I have not tested on any others.

when using -edition 4. it throws an error converting the number from a string to a number.
changing line 4092 to read
                    $openImage = $openWim[[Int32]([string]$Edition)]
resolved it for me.
for some reason I have to cast the string as a string before casting at as an INT.

**Comment by BenjaminArmstrong** [comment]
Mike – I believe this is feedback on Convert-WindowsImage

**Comment by BladeFireLight** [comment]
Yes this is for Convert-WindowsImage.ps1

**Comment by scooley** [comment]
Thank you, Matt.

@BenjaminArmstrong , @mebersol one of you willing to review and merge :)?

**Comment by mebersol** [comment]
I merged in this fix.  Pretty soon, we will move from custom DISM commands to the DISM cmdlets, and this logic will get reworked a little.
