### ISSUE TITLE
Install-ContainerImage fails when executed via WinRM on TP5 Azure VM

### ISSUE THREAD

**Issue by selvik** [Microsoft/Virtualization-Documentation#228]
Hi all,
I am trying to create a container host on a TP5 VM on Azure. When I try to install the container images, I get this error. Would anyone know why? Thanks in advance!
-Selvi

Command executed via WinRM: powershell -command "& {&'Install-ContainerImage' -Name WindowsServerCore}"
Stdout:
`WARNING: Cannot bind argument to parameter 'fastPackageReference' because it is an empty string.`
`WARNING: The property 'version' cannot be found on this object. Verify that the property exists.`
`WARNING: The property 'Name' cannot be found on this object. Verify that the property exists.`
`WARNING: Cannot find path 
'C:\Users\ubuntu\AppData\Local\ContainerImage\ContainerImageGallery_ContainerImageSearchIndex.txt' because it does not 
exist.`
`WARNING: Cannot find drive. A drive with the name 'CleanUp' does not exist.`
`WARNING: Save-HTTPItem: Bits Transfer failed. Job State:  ExitCode = -2147023651`
`WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell, stderr: PackageManagement\Save-Package : No match was found for the specified search criteria and package name 
'WindowsServerCore'. Try Get-PackageSource to see all available registered package sources.
At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:492 char:23`
`+ ...   $downloadOutput = PackageManagement\Save-Package @PSBoundParameters`
`+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage`
`The property 'Name' cannot be found on this object. Verify that the property exists.`
`At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:494 char:5`
`+     $Destination = GenerateFullPath -Location $Location`
`+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`+ CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException`
`+ FullyQualifiedErrorId : PropertyNotFoundStrict`
`Install-ContainerOSImage : Cannot bind argument to parameter 'WimPath' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:502 char:39`
`+     Install-ContainerOSImage -WimPath $Destination`
`+                                       ~~~~~~~~~~~~`
`+ CategoryInfo          : InvalidData: (:) [Install-ContainerOSImage], ParameterBindingValidationException`
`+ FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Install-ContainerOSImage`
`Remove-Item : Cannot bind argument to parameter 'Path' because it is null.`
`At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:512 char:8`
`+     rm $Destination`
`+        ~~~~~~~~~~~~`
`+ CategoryInfo          : InvalidData: (:) [Remove-Item], ParameterBindingValidationException`
`+ FullyQualifiedErrorId :` `ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveItemCommand, exit: 0`

**Comment by StefanScherer** [comment]
I also got this "Bits Transfer failed" error provisioning with Packer which also does it via WinRM. My workaround is to use a [scheduled task](https://github.com/StefanScherer/packer-windows/blob/4fddf51ea44c2264e1ccf33db0f70d28ca14884e/scripts/docker/install-docker.ps1) and run the provision script in the interactive desktop. I hope there is a better way to do it.

**Comment by selvik** [comment]
Thanks, @StefanScherer. Going to give this a try.

**Comment by selvik** [comment]
@StefanScherer Works like a charm! Thank you. 💯

**Comment by PatrickLang** [comment]
Closing this out - we have images that are ready to run containers on Azure for both Windows Server
