### ISSUE TITLE
Does not work on WIM created via New-WindowsImage

### ISSUE THREAD

**Issue by BladeFireLight** [Microsoft/Virtualization-Documentation#23]
A WIM with a single edition created via New-WindowsImage fails when trying to mount the edition due to no value in ImageFlags
changein the code  on 4075 from 
                # If there's only one image in the WIM, just selected that. 
                 if ($openWim.Images.Count -eq 1) {  
                     $Edition   = $openWim.Images[0].ImageFlags 
                    $openImage = $openWim[$Edition] 
                  } else { 

to 
           # If there's only one image in the WIM, just selected that.
            if ($openWim.Images.Count -eq 1) 
            { 
                $Edition   = 1 
            }
 got it working.

**Comment by BladeFireLight** [comment]
this is for Convert-WindowsImage.ps1

**Comment by mebersol** [comment]
This is fixed in the private WIndows fork, but is tied up in the move to DISM cmdlets.  I will bring this in by next few days.  

Thanks for reporting!

**Comment by mebersol** [comment]
Fixed with https://github.com/Microsoft/Virtualization-Documentation/commit/75e3dc8e279679bf2f93da64355a3632f06bde58
