### ISSUE TITLE
can't run 'docker images' after upgrade from 14238 to 14332

### ISSUE THREAD

**Issue by burtonrodman** [Microsoft/Virtualization-Documentation#234]
I know i'm playing with fire here.  I was biting at the bit to try a Hyper-V container on Windows 10 so I ran the QuickStart script for configuring an existing Windows Server 2016 box, which all seemed to work up to the point that I did a docker run with a nano image, my system would blue screen.

So after upgrading to 14332 i thought i'd try again.  I ran docker images (which worked previously) and now it errors saying:

An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/json: open //./pipe/docker_engine: The system cannot find the file specified.

I'm not really expecting a solution, but mostly wanted to share my experience.

If there's a doc on getting Windows 10 working with Hyper-V containers that I'm not seeing, please share.

**Comment by PatrickLang** [comment]
Unfortunately, Hyper-V containers are not working in the Windows Insider builds 14328 and 14332 for other reasons. More details are available here: https://social.msdn.microsoft.com/Forums/en-US/03434a94-df41-4dbf-9668-34526a39389b/installcontainerimage-nanoserver-windowsservercore-on-windows-10-143321001-gives-certificate?forum=windowscontainers

Once we have a Windows Insider build that's ready to test, we'll be sure to post updated documentation on how to use it.

With that said, the Docker daemon should still be able to start, but importing the base image and running containers will cause problems. Try looking at C:\ProgramData\docker\daemon.log for more info and feel free to post a log here.

**Comment by PatrickLang** [comment]
Closing since this refers to old builds. If you have problems with Docker commands failing in the future, please go ahead and open a new issue at https://github.com/docker/docker since we have developers tracking Windows issues there too. Thanks!
