### ISSUE TITLE
Is it posible to place this in a module?

### ISSUE THREAD

**Issue by BladeFireLight** [Microsoft/Virtualization-Documentation#24]
I tried to wrap this in a module for better portabiltiy, and it failed horribly. I think there is a scoping issue. Not to mention functions inside of functions but fixing that did not resolve the error.

**Comment by BladeFireLight** [comment]
I guess I should mention this is for Convert-WindowsImage.ps1

**Comment by BladeFireLight** [comment]
This may be why my attempt to add to ta module failed
https://connect.microsoft.com/PowerShell/Feedback/Details/804580

**Comment by scooley** [comment]
Cute.  I know Artem (one of the maintainers for this code) wanted to make it a module.  I'll see if I can get him in the thread :)

**Comment by BladeFireLight** [comment]
there has been a lot of changes to the file lately, I can't keep up. Or I would have done a pull request. modularization is a major change.

**Comment by scooley** [comment]
Absolutely.  Check back in a month or two.

We're in the process of consolidating two versions of this script.  The script we've been using in Hyper-V unintentionally diverged from the one folks could download -- different maintainers, etc -- we're fixing it :).

**Comment by BladeFireLight** [comment]
Little longer then I was hoping for. There is no license in this Repo, can I use some of the code from Convert-WindowsImage in my own projects?

**Comment by scooley** [comment]
Oops, just tacked an MIT license to the repo.

Yes :).  Party on.

**Comment by mebersol** [comment]
BladeFireLight - I have one more small PR coming this week and maybe one next week, but the bulk of the churn should be complete.  You don't need to wait to propose changes.

**Comment by scooley** [comment]
Pinging @pronichkin now that he's on GitHub :).

**Comment by neilpeterson** [comment]
I'm assuming that this is no longer an issue, if so, please advise and we can re-open.
