### ISSUE TITLE
Debug .NET in Windows

### ISSUE THREAD

**Issue by neilpeterson** [Microsoft/Virtualization-Documentation#243]
This issue is being used to track Docker related documentation.

| Status | Platform | Site | Staged Content | Live Content |
| :-: | :-: | :-: | :-: | :-: |
| Planned | Windows | MSDN | NA | NA |

**Comment by AshleyPoole** [comment]
I'd love to see this documentation created. I see we can debug easily .NET Core in Linux containers but I'd like to see a guide on the Windows side if possible. (I guess that also needs the Docker Tools for VS to be updated too).
