### ISSUE TITLE
Breakpoint Debugging in Visual Studio

### ISSUE THREAD

**Issue by neilpeterson** [Microsoft/Virtualization-Documentation#247]
This issue is being used to track Docker related documentation.

| Status  | Platform | Site | Staged Content | Live Content |
|:---:|:---:|:---:|:---:|:---:|
Planned  | Linux | NA | NA | [Azure.com](https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-edit-and-refresh/)

**Comment by friism** [comment]
cc @ManoMarks

**Comment by allclark** [comment]
https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-edit-and-refresh/

**Comment by neilpeterson** [comment]
@allclark - Thanks Allen. I am closing this out as complete.
