### ISSUE TITLE
Install-ContainerImage on TP5 fails after download with create vm utility error: The system cannot find the file specified 

### ISSUE THREAD

**Issue by sflanders** [Microsoft/Virtualization-Documentation#252]
[192.168.137.102]: PS C:\> Install-ContainerImage -Name NanoServer -Version 10.0.10586.0 -Verbose
VERBOSE: Saving to C:\Users\ADMINI~1\AppData\Local\Temp\NanoServer.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloading NanoServer. Version: 10.0.10586.0
VERBOSE: https://pshctnoncdn.blob.core.windows.net/pshctcontainer/CBaseOs_th2_release_10586.0.151029-1700_amd64fre_NanoServer_en-us.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Importing function 'Invoke-HTTPClient'.
VERBOSE: Importing function 'Save-HTTPItem'.
VERBOSE: Importing function 'Save-RSTBlobItem'.
VERBOSE: Downloaded in 0 hours, 0 minutes, 11 seconds.
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
 

I've tried with and without the "-Version ..." and it gets same issue.

**Comment by mebersol** [comment]
There is no base image with version 10.0.10586.0

Run Find-ContainerImage to determine which images are available

**Comment by sflanders** [comment]
Sure there is.  Here's the response from running the command

**[192.168.137.102]: PS C:\> Find-ContainerImage

Name                 Version                 Description                        
----                 -------                 -----------                        
NanoServer           10.0.10586.0            Container OS Image of Windows Se...
WindowsServerCore    10.0.10586.0            Container OS Image of Windows Se...**



[192.168.137.102]: PS C:\> 
[192.168.137.102]: PS C:\> Install-ContainerImage -Name NanoServer -Verbose
VERBOSE: Saving to C:\Users\ADMINI~1\AppData\Local\Temp\NanoServer.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloading NanoServer. Version: 10.0.10586.0
VERBOSE: https://pshctnoncdn.blob.core.windows.net/pshctcontainer/CBaseOs_th2_release_10586.0.151029-1700_amd64fre_NanoServer_en-us.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Importing function 'Invoke-HTTPClient'.
VERBOSE: Importing function 'Save-HTTPItem'.
VERBOSE: Importing function 'Save-RSTBlobItem'.
VERBOSE: Downloaded in 0 hours, 0 minutes, 12 seconds.
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

**Comment by mebersol** [comment]
Interesting - that image should have been removed, will follow up with OneGet team.  The TP4 Xenon image is not supported on TP5 container host, and you need to upgrade your ContainerImage provider to access the TP5 image.  

Migrate from Windows Server 2016 Technical Preview 4 (TP4) to Windows Server 2016 Technical Preview 5 (TP5)

The ContainerImage provider version 0.6.x.x only works with the TP5 hosts. If you have an old TP4 host, although you can still install this version of ContainerImage provider, you will run into an error when trying to use any of the cmdlets mentioned above.

From the ContainerImage GitHub project: 

In order to migrate to the TP5 Containers, you will need to:
1.Upgrade the host to TP5 host with version 10.0.14300.0
2.Install and import the ContainerImage provider with version 0.6.x.x
3.Use the cmdlets above to search/install/download the TP5 container OS images

**Comment by sflanders** [comment]
I'm already on TP5, 10.0.14300.0.   I also ran all the commands to show what i have on the host.  As you can see i still get the same error.

[192.168.137.102]: PS C:\> [environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14300  0       

[192.168.137.102]: PS C:\> Get-Package
Name                           Version          Source                           Summary                                                                                 
----                           -------          ------                           -------                                                                                 
ContainerImage                 0.6.4.0          https://www.powershellgallery... This is a PackageManagement provider module which helps in discovering, downloading a...
ContainerProvider              0.5.2            https://www.powershellgallery... ContainerProvider is a Windows PowerShell module to find, save or install Windows Ser...

[192.168.137.102]: PS C:\> Find-ContainerImage

Name                 Version                 Description                        
----                 -------                 -----------                        
NanoServer           10.0.10586.0            Container OS Image of Windows Se...
WindowsServerCore    10.0.10586.0            Container OS Image of Windows Se...

[192.168.137.102]: PS C:\> Install-ContainerImage -Name NanoServer -Version 10.0.10586.0
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

**Comment by sflanders** [comment]
I even tried the offline approach

[192.168.137.102]: PS C:\container-image> Save-ContainerImage -Name NanoServer -Destination c:\container-image\NanoServer.wim -Verbose
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Downloading NanoServer. Version: 10.0.10586.0
VERBOSE: https://pshctnoncdn.blob.core.windows.net/pshctcontainer/CBaseOs_th2_release_10586.0.151029-1700_amd64fre_NanoServer_en-us.wim
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''className' = win32_operatingsystem,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
VERBOSE: Importing function 'Invoke-HTTPClient'.
VERBOSE: Importing function 'Save-HTTPItem'.
VERBOSE: Importing function 'Save-RSTBlobItem'.
VERBOSE: Downloaded in 0 hours, 0 minutes, 11 seconds.

[192.168.137.102]: PS C:\container-image> Install-ContainerOSImage -WimPath c:\container-image\NanoServer.wim -Force
Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create utility VM image VHD with error: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

**Comment by mebersol** [comment]
What happens after you remove ContainerProvider 0.5.2?

**Comment by sflanders** [comment]
How do i remove?  i'm only seeing the Install-PackageProvider
