### ISSUE TITLE
Enabling Users to run this in an offline environment

### ISSUE THREAD

**Issue by heoelri** [Microsoft/Virtualization-Documentation#254]
Hi Folks,

i've tried to run this script in an offline or proxy environment. Without success. 

Partially caused by the download of NSSM.

Maybe it's possible to move NSSMUri from a hardcoded URI in Line 730 to the parameters section to enable users to specify the part to a downloaded copy of nssm:

`[string]
    [ValidateNotNullOrEmpty()]
    $nssmUri =  "https://nssm.cc/release/nssm-2.24.zip",`

This enables us to download the required components first and add them as a parameter:

`.\Install-ContainerHost.ps1 -DockerPath C:\docker\docker.exe -DockerDPath C:\docker\dockerd.exe -SkipImageImport -Nssmuri C:\docker\nssm-2.24.zip`

Kind regards
Heyko

**Comment by neilpeterson** [comment]
To quickly unblock you, these articles can be followed for offline installation and configuration.

[Windows Server](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment)

[Nano Server](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment_nano)

[Offline Image Installation](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_images#offline-installation)

**Comment by PatrickLang** [comment]
Closing - these workarounds were for TP5. Now you can use docker pull / docker save / docker load to handle images offline.
