### ISSUE TITLE
TP5: Container hangs itself up after adding NetworkController feature & get-windowsfeature

### ISSUE THREAD

**Issue by mathiasconradt** [Microsoft/Virtualization-Documentation#269]
Related to https://github.com/Microsoft/Virtualization-Documentation/issues/155, but this is not about the documentation/clarification, but about the behaviour itself.

This seems to have been a bug in TP4, as Neil Peterson confirmed via Twitter (http://superuser.com/a/1048289/46725), but it still exists in TP5 as well with slightly different behaviour. Here is a screencast where the container hangs himself up once trying to add the NetworkController windows feature.
The entire container hangs, not even possible to stop it via `docker stop` anymore.

Here is a screencast: https://screenrecordings.tinytake.com/sf/NjY5MDI3XzMyMTExMDE

How to reproduce it:

1. Start container:
`docker run --name="wincore" -it windowsservercore powershell`

2. Add Network Controller
`add-windowsfeature networkcontroller`
It tells you that you need to restart the server (assuming it's meant to restart the container. This should be clarified in the documentation as mentioned in https://github.com/Microsoft/Virtualization-Documentation/issues/155).

3. On the container host, run:
`docker restart wincore`
`docker attach wincore`

4. Inside the container, run:
`get-windowsfeature *net*`
It will hang endlessly at 57%, neverending.

5. Try to stop the container from outside:
`docker stop wincore`
Hangs endlessly as well. Only way to resolve it is to actually reboot the whole container host machine. 

6. After the reboot of the container host, run again:
`docker start wincore`
`docker attach wincore`

7. Inside the container:
`get-windowsfeature *net*`

Now, this time the call does not hang anymore, but unfortunately the NetworkController is still not installed and the status is back to "Available".

```
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   2b97201
 Built:        Tue Apr 26 23:51:36 2016
 OS/Arch:      windows/amd64
```

```
Windows Server 2016 Datacenter Technical Preview 5
Build 14300.rs1_release_svc.160324-1723)
```

**Comment by JMesser81** [comment]
Hi Mathias - 

May I ask why you are trying to run Network Controller from within a container? This is not a supported configuration at this time. 

Jason

**Comment by mathiasconradt** [comment]
@JMesser81 I was having problems with a HttpListener in my .net application and thought it was related to the NetworkController, but I meanwhile figured out that it's not related. Closing this ticket.
