### ISSUE TITLE
TP5: Change DockerData location

### ISSUE THREAD

**Issue by Mirabis** [Microsoft/Virtualization-Documentation#270]
Line 80: $global:DockerData = "$($env:ProgramData)\docker" 

Specifies ProgramData, but as that is pretty small on my 120GB Host SSD, can I change that field to *:\Docker where's TB's of free space?

Or is there a reason it goes into ProgramData?

**Comment by mebersol** [comment]
Install scripts don't currently drive Docker policy, they just reflect what is currently a non-configurable default.

@jhowardmsft - can you comment on Docker data configuration plan for RTM?

**Comment by jhowardmsft** [comment]
As is now. No plans to change the default from programdata. But it can be configured to where-ever users want. Exactly the same as linux where it defaults to `/var/lib/docker`

**Comment by Mirabis** [comment]
Okay thanks :) I did not look for a change in the default location, but merely wondered if it is supported to change the location. I already modified the install script directories / nssm.exe configs to reflect the new directory.

It is just that by coincidence my entire Storage Spaces pool disappeared after that change (not sure if it was related or not). Either way, thanks for the response :)

**Comment by jhowardmsft** [comment]
Totally supported. `dockerd --graph <some directory> --pidfile <somedirectory\daemon\docker.pid>` for example.
