### ISSUE TITLE
Networking issues with TP5 on Azure

### ISSUE THREAD

**Issue by mathiasconradt** [Microsoft/Virtualization-Documentation#272]
The following issues did not occur with my TP5 on-premise installation, but **only occur on Azure**.

# 1. Can only reach http listener inside Docker container on port 8082 when adding firewall rule to the host

I start a http listener inside the docker container on port 8082. I can reach it via "`wget http://<containerHostname>:8082`" as well as "`wget http://<containerIP>:8082`" from inside the container. But the same does not work from the container host:

I can only reach "`wget http://<containerIP>:8082`" when I **add a firewall inbound rule for port 8082 to the host**, which in my opinion does not make much sense, since we are talking about the communication between `host->container`, not the outside communication `public->host`. It's not clear to me why firewall rules applied to the host have an effect to the container (=the container is re-using the firewall rules of the host). 
Sorry, I'm not a networking expert, maybe there is a technical explanation for that - why it makes sense.

# 2. Host cannot resolve container hostname (WIN-DE6U4068NAF)

Even with the firewall rule, I cannot reach the http listener of the container via hostname: "`wget http://<containerHostname>:8082`". The host cannot resolve the hostname of the container properly.
(I get the container hostname by typing `hostname` inside the container - it's: WIN-DE6U4068NAF. The container hostname differs from the hostname that I get in the `docker inspect` response.)

`docker inspect` output: http://pastebin.com/LYg4KvBE

Pinging works fine on-premise, it does not work on Azure:

On-Premise works fine:

```
PS C:\Windows\system32> ping WIN-DE6U4068NAF

Ping wird ausgeführt für WIN-DE6U4068NAF [fe80::8c5:22c6:b1d9:a3d%3] mit 32 Bytes Daten:
Antwort von fe80::8c5:22c6:b1d9:a3d%3: Zeit<1ms
Antwort von fe80::8c5:22c6:b1d9:a3d%3: Zeit<1ms
Antwort von fe80::8c5:22c6:b1d9:a3d%3: Zeit<1ms
Antwort von fe80::8c5:22c6:b1d9:a3d%3: Zeit<1ms

Ping-Statistik für fe80::8c5:22c6:b1d9:a3d%3:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 0ms, Maximum = 0ms, Mittelwert = 0ms
```

On Azure, it cannot resolve:

```
PS C:\Windows\system32> ping WIN-DE6U4068NAF
Ping request could not find host WIN-DE6U4068NAF. Please check the name and try again.
```

**Note that both points mentioned above work fine with my on-premise installation, just not on Azure.**

**Comment by pmsousa** [comment]
@mathiasconradt Just to clarify on point **4.**, you have inbound rule on Network Security Group you have (?) an Inbound Security Rule to "allow tcp/80" to the host. ([Example](http://images.michaelsync.net/images/2015/09/Azure-VM-Firewall1.png))

**Comment by mathiasconradt** [comment]
@pmsousa Ahem, sorry, I totally forgot about setting the rule on Azure! I just just setting it on the TP5 host machine. Now actuall everything from outside works fine for me. I can both reach any httpd server that I run on the host (i.e. Apache httpd), or I can run a http server inside the container and I can reach it from outside through the host's hostname or public IP (http://xxxx.westeurope.cloudapp.azure.com:80). This makes two of my previous reported issues obsolete.

**Comment by mathiasconradt** [comment]
@pmsousa I think I should delete this ticket again, because it's a different topic that your initial problem (which actually works on my side now after I added the Azure Firewall rule that I forgot.)
Maybe better to create a new separate ticket for your problem. If you want me to check anything on my machine where everything is working - for you to compare, let me know.

The remaining above two issues are actually no show stoppers and maybe even intended to work like that, not sure.

**Comment by pmsousa** [comment]
Go ahead and close this one. I'll open a ticker has soon I can get my subscription access again and do further testing. This afternoon my spending limit for this subscription was reached, due to several VMs being "mysteriously" changed from Stopped (Deallocated) to only Stopped during the weekend and burning ~350€!!! Still have to figure it out with Support... :(

**Comment by mathiasconradt** [comment]
Closing this ticket (see comment above)

**Comment by mathiasconradt** [comment]
Closing this ticket (see comment above)
