### ISSUE TITLE
How to restart powershell without admin privileges in Server Core?

### ISSUE THREAD

**Issue by wbradney** [Microsoft/Virtualization-Documentation#288]
I'm new to containers and following the new quick start here: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
It asks you to restart Powershell not as administrator. So I closed the shell (to get back to a blank screen in Server Core), and then used Task Manager (Ctrl-Shift-ESC) to run a new Powershell task. This is by default run as Administrator (even says so in the "Create new task" prompt). Even if I start cmd and then Powershell, how would I start it without admin rights? Do I need to add a regular user to my TP5 VM?

**Comment by neilpeterson** [comment]
Thanks for the feedback, agree this was a little confusing. I've updated the text for clarity.

**Comment by wbradney** [comment]
Thanks. I had forged ahead anyway as admin without any adverse consequences. Having the documentation on how to play with these bleeding edge features is invaluable and much appreciated.
