### ISSUE TITLE
dockerd --register-service errors out

### ISSUE THREAD

**Issue by mbharadwaj** [Microsoft/Virtualization-Documentation#292]
Error message is:
flag provided but not defined: --register-service

On TP5/VirtualBox (osx)

Trying out steps from:
https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by neilpeterson** [comment]
@mbharadwaj Did you download dockerd.exe today? Can you provide the output of the command `dockerd --version`? The build should be '8e92415'. If you have an earlier build the register service command will not work. 
```
PS C:\> dockerd --version
Docker version 1.12.0-dev, build 8e92415
```

If this is the case, you can delete 'dockerd.exe' and re-run the command which should pull the new version.

Thanks

neilp

**Comment by mbharadwaj** [comment]
Thank you.

The build was 2b97201.

I have deleted the old version and when I get new, I still see the version that is tagged "2b97201".

**Comment by StefanScherer** [comment]
I've downloaded the binaries (8e92415) as described in the quickstart guie into a VirtualBox TP5 VM and registering the service works fine.

**Comment by mbharadwaj** [comment]
I have tried this a few times and I only get the 2b97201 version.

**Comment by StefanScherer** [comment]
Really?
```
Invoke-WebRequest https://aka.ms/tp5/b/dockerd -OutFile $env:ProgramFiles\docker\dockerd.exe
```
did work for me an hour ago.

**Comment by StefanScherer** [comment]
Do you have old binaries in C:\Windows\system32\docker*.exe ?

**Comment by mbharadwaj** [comment]
No, i don't have them there. I had checked all the folders in path.

**Comment by mbharadwaj** [comment]
oh! my bad. i had missed the "b" in the path.

I could not cut/paste it and had typed it out and i had missed the "b"

Invoke-WebRequest https://aka.ms/tp5/dockerd -OutFile $env:ProgramFiles\docker\dockerd.exe

Trying the proper url now...

**Comment by mbharadwaj** [comment]
ok - that worked! sorry about the confusion caused. thanks for all the help.
