### ISSUE TITLE
failed to register layer: layer does not exist

### ISSUE THREAD

**Issue by kobenauf** [Microsoft/Virtualization-Documentation#298]
Running steps here: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_10#2-install-docker

After this step:
`docker pull microsoft/sample-dotnet`
Received this error:
`failed to register layer: layer does not exist`

**Comment by StefanScherer** [comment]
@kobenauf You are working with Windows 10, right? Then you only have the `nanoserver` base image, just try to run
```
docker images
```
and you cannot install and run the `windowsservercore` base image in Windows 10, at least not yet.

The image you are trying to pull is based on `windowsservercore`. And at the moment docker does not pull these base images automatically like it's done on Linux. So this error appears.

Search for docker images that are based on `nanoserver`.

**Comment by neilpeterson** [comment]
This is know and is being worked on.

ping @PatrickLang

**Comment by PatrickLang** [comment]
Can you share your output from `docker images` so I can confirm it's the same issue we're looking into?

**Comment by kobenauf** [comment]
@PatrickLang
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nanoserver          10.0.14300.1016     3f5112ddd185        3 weeks ago         810.2 MB
nanoserver          latest              3f5112ddd185        3 weeks ago         810.2 MB

**Comment by PatrickLang** [comment]
Thanks! We just pushed a new image that works with nanoserver 10.0.14300.1016.

Here's the latest nanoserver image IDs along with a few images we fixed. 
```
C:\golang-test>docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
microsoft/sample-dotnet   nanoserver          28da49c3bff4        50 minutes ago      918.3 MB
microsoft/sample-golang   nanoserver          ee3280b29cf4        2 hours ago         1.037 GB
nanoserver                10.0.14300.1016     3f5112ddd185        3 weeks ago         810.2 MB
nanoserver                latest              3f5112ddd185        3 weeks ago         810.2 MB
```

The rest are in progress, so if you run into more problems after today, please let us know.

**Comment by neilpeterson** [comment]
Confirmed to be fixed on my system. I am going to close the issue. Thanks @kobenauf for reporting it.

**Comment by chlowell** [comment]
I'm seeing the same error following the [Windows 10 Quick Start](https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_10#3-install-base-container-images) steps today:

```
C:\>docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
microsoft/nanoserver   10.0.14300.1030     3a703c6e97a2        3 weeks ago         969.8 MB
nanoserver             latest              3a703c6e97a2        3 weeks ago         969.8 MB

C:\> docker pull microsoft/sample-dotnet
Using default tag: latest
latest: Pulling from microsoft/sample-dotnet
233dc4ad52a9: Extracting [==================================================>] 1.089 kB/1.089 kB
d0f5e9f75fab: Download complete
65b8e54dfec0: Download complete
4a1985a645bf: Download complete
9c0b01ae842a: Download complete
3feb02208c35: Download complete
a66d54f641cc: Download complete
4d9bf08b3d20: Download complete
failed to register layer: layer does not exist
```

**Comment by PatrickLang** [comment]
We still need to push new images that are built against this image:
```
microsoft/nanoserver   10.0.14300.1030     3a703c6e97a2        3 weeks ago         969.8 MB
```

Unfortunately we're still working through a few issues on our side around this. I'll let you know when we have a new one available.

In the meantime, you should be able to manually build the other sample Dockerfiles in this repo

**Comment by StefanScherer** [comment]
So there is a newer OS image for nanoserver. I ran a `Find-ContainerImage` today in my TP5 box and still found the NanoServer 1016. Is this correct?

```
C:\Users\vagrant> find-containerimage

Name                           Version          Source           Summary
----                           -------          ------           -------
NanoServer                     10.0.14300.1016  ContainerImag... Container OS Image of Windows Server 2016 Tec...
WindowsServerCore              10.0.14300.1000  ContainerImag... Container OS Image of Windows Server 2016 Tec...
```

**Comment by neilpeterson** [comment]
@PatrickLang can correct me if I have this wrong, but I believe the issue starts with Windows 10 previews releasing at a quicker cadence than server, so Windows 10 > version than server, and thus we have two different nano server base images 1016 for server and 1030 for windows 10.

These issues being reported should only effect Windows 10. I am walking through an updated Windows 10 quick start now and will update the doc once completed.

**Comment by friism** [comment]
@neilpeterson well, it may also be a problem if people grab the windowsservercore / nano tar and `load` it into a WS2016 engine. I tried that and got the same error

**Comment by neilpeterson** [comment]
@friism, good point, make sense.

**Comment by StefanScherer** [comment]
ok, even a `packer build` for TP5 still installs nanoserver base image 1016.

Will the `docker pull` work for both Win10/2016, so nano application images on Docker Hub will work for both users?

**Comment by PatrickLang** [comment]
@StefanScherer that's the plan. Right now we're using 1030 on Windows 10 Insider builds as a workaround. The images on Docker Hub are still built against 1016 and work correctly on Windows Server 2016 TP5. We will be able to unify the Windows 10 and Windows Server 2016 TP5 guidance once we get some issues worked out.

**Comment by StefanSteiner** [comment]
It would be good to have a notice at: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10 
warning people the "4. Deploy Your First Container" step is broken . The Install-ContainerOSImage issue with the prior preview update was frustrating and now this issue has cropped up.

**Comment by neilpeterson** [comment]
Step 4 of this quick start has been updated to something that works given the issue. We will revert back once the issue has been resolved.

**Comment by StefanSteiner** [comment]
@neilpeterson Thanks!
