### ISSUE TITLE
Script Enable-NestedVm not working build 14361

### ISSUE THREAD

**Issue by visual14ph** [Microsoft/Virtualization-Documentation#299]
The error message is basically

Set-VMProcessor: Failed to modify device ' Processor '.
Cannot modify property.

For now is there any alternative way to enable nested virtualization?

**Comment by neilpeterson** [comment]
@visual14ph - you can try the commands without the Enable-NestedVM commands. These can be found [here](https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/nesting).

If they do not work can you verify that you are on a Windows 10 build that is greater than 10565. This can be found using:

```none
powershell [System.Environment]::OSVersion.Version
```

**Comment by visual14ph** [comment]
@neilpeterson - Had already tried by the MSDN article and the error is the same.

I'm on build 14361 Anniversary Update rs1

**Comment by neilpeterson** [comment]
@scooley Sarah, can anyone from your team help?

**Comment by scooley** [comment]
+Theo

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Jun 10, 2016 at 9:27 AM -0700, "Neil Peterson" <notifications@github.com<mailto:notifications@github.com>> wrote:


@scooley<https://github.com/scooley> Sarah, can anyone from your team help?

-

**Comment by scooley** [comment]
Yes!  Adding @theodthompson.

**Comment by theodthompson** [comment]
This is an error in build 14361; sorry about that. It is fixed in later builds.

For now, you can disable Virtualization Based Security for the VM by using an opt-out:
`Set-VMSecurity -VMName <vmname> -VirtualizationBasedSecurityOptOut $true`

Please look for documentation coming in the near future to cover this case.

**Comment by visual14ph** [comment]
Thanks. it is works now
