### ISSUE TITLE
Container command ping not found

### ISSUE THREAD

**Issue by sjey** [Microsoft/Virtualization-Documentation#300]
Trying to run the container in mac OS X. But for some reason, I get the following error.

docker: Error response from daemon: Container command 'ping' not found or does not exist.. 

Is mac not supported yet for this container?

**Comment by friism** [comment]
@sjey what container are you trying to run?

**Comment by neilpeterson** [comment]
@sjey is this a Windows Server VM on mac?

**Comment by sjey** [comment]
@neilpeterson/@friism, yes running a microsoft/iis windowsserver image in mac.

Looks like cross os is not supported at this time I believe

**Comment by friism** [comment]
@sjey you have to have a WS2016 TP5 VM. On Mac, you can get that going for free with VirtualBox. See these guides:

 * http://blog.couchbase.com/2016/april/windows-server-2016-virtualbox-docker
 * http://blog.couchbase.com/2016/april/setup-docker-windows-server-2016
 * https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by PatrickLang** [comment]
Closing - please try one of the links above
