### ISSUE TITLE
IIS on docker results in 404

### ISSUE THREAD

**Issue by mabead** [Microsoft/Virtualization-Documentation#301]
I am trying to follow the flow presented in the following [docker quick start](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server). I was able to install the base images as well as pulling the IIS image through `docker pull microsoft/iis:windowsservercore`. I then started this container through `docker run -d -p 80:80 microsoft/iis:windowsservercore ping -t localhost`. 

I then installed firefox on my docker host (that is running within Azure) and I simply open a browser at the address "http://localhost". This results in 404 not found error. 

If I open a browser on my machine (not on the docker host) and I try to connect with firefox using the ipaddress, I have the same error. 

Note that if I connect on my container through `docker exec -it <container> powershell` and run "iisreset /status", it displays the following:
```
Status for Windows Process Activation Service ( WAS ) : Running
Status for World Wide Web Publishing Service ( W3SVC ) : Running
```
Also note that I don't have any IIS logs:
```
PS C:\Windows\System32\LogFiles> dir


    Directory: C:\Windows\System32\LogFiles


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        3/25/2016  11:22 AM                Firewall
d-----         5/5/2016  10:28 PM                Scm
d-----        5/13/2016  11:11 PM                SQM
d-----        6/10/2016   2:12 PM                WMI
```
Are you sure that the documentation/image work?

**Comment by neilpeterson** [comment]
I've just run through the doc, all steps worked as expected.

For http://localhost, this will not work and is know, but you should be able to connect to the IIS endpoint from a remote system.

I am not sure about the IIS logs, but service appears to be running. Can you verify connectivity to the container host from your system?

**Comment by StefanScherer** [comment]
@mabead To connect from your machine to the IP address of the Azure VM you need an incoming rule in the network security group. The `docker run -d -p 80:80 ...` opens the firewall port only in the VM, but not for the public IP address in Azure.

As you have installed Firefox on your docker host you can try opening the web site with the containers IP address. In PowerShell you can do this with by retrieving the container id and inspecting that container.

```
C:\> docker ps
CONTAINER ID        IMAGE                             COMMAND               CREATED             STATUS              PORTS                NAMES
9025270195bf        microsoft/iis:windowsservercore   "ping -t localhost"   3 minutes ago       Up 3 minutes        0.0.0.0:80->80/tcp   sad_rosalind
```

Now you can retrieve the IP address of the container with

```
C:\> docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" 9025270195bf
172.21.98.241
```

Now start your default browser with that IP address:

```
C:\> start http://$(docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" 9025270195bf)
```

Of course if you give your container a name with `docker run -d -p 80:80 --name=myiis ...` you can use that name instead of the container id.

**Comment by mabead** [comment]
We can clearly see that I am new to using Azure:( I tried your two approaches:

- From the docker host, connect to the ip address of the docker container.
- From my dev box (outside of azure), connect to the ip address of the docker host (after adding an incoming rule) in the network security group. 

Both approaches work. Thanks a lot for your help.

That being said, I think that the documentation could be clarified to cover these cases.

**Comment by neilpeterson** [comment]
@StefanScherer thanks for the fix, missed that this was in Azure.

@mabead this for the doc feedback. We intentionally went with very scoped scenarios so as to avoid involving too much tech. In the case of this doc, Azure is not in scope. That said, I think adding a note to call out the NSG need in Azure make sense and can be done without adding too much cruft. I will look into it.

neilp

**Comment by neilpeterson** [comment]
I've added a not about the Azure NSG.

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_images#1-container-image-manual

Thanks again.

**Comment by mabead** [comment]
@neilpeterson Great! This was added in step 3 of the Quick Start guide. I suggest that you also add the note to step 2 since it will usually be done before step 3.

**Comment by neilpeterson** [comment]
@mabead done - thanks.
