### ISSUE TITLE
OpenSSL Installer Changed from Source

### ISSUE THREAD

**Issue by lmayorga1980** [Microsoft/Virtualization-Documentation#303]
OS: Windows 7 SP1 (Powershell v5.0)

https://github.com/Microsoft/Virtualization-Documentation/blob/live/windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1#L103

It seems that now is **h** https://slproweb.com/products/Win32OpenSSL.html

Changed the URL to ...

`[String] $OpenSSLDownloadPath = "https://slproweb.com/download/Win64OpenSSL_Light-1_0_2h.exe",`

I wonder why it does make a reference to **/usr/local/bin**

![screen shot 2016-06-10 at 2 57 51 pm](https://cloud.githubusercontent.com/assets/3172378/15975513/d203c596-2f1b-11e6-93e6-9d7820d2ba0f.png)

**Comment by lmayorga1980** [comment]
Uhmm.. This guy helped me

`$env:OPENSSL_CONF="C:\Program Files\OpenSSL\bin\openssl.cfg"`

**Comment by StefanScherer** [comment]
@lmayorga1980 Indeed. OpenSSL switched from `g` to `h` removing the old download link. Have you thought about sending a PR?

**Comment by lmayorga1980** [comment]
I will

On Saturday, June 11, 2016, Stefan Scherer <notifications@github.com> wrote:

> @lmayorga1980 <https://github.com/lmayorga1980> Indeed. OpenSSL switched
> from g to h removing the old download link. Have you thought about
> sending a PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Microsoft/Virtualization-Documentation/issues/303#issuecomment-225366276>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADBoGnadrYuCWbT_t5v0V1DHl-fzbRmyks5qKsfUgaJpZM4IzOzO>
> .
>


-- 
Luis Mayorga
Software & Devops Engineer
C. +1-703-407-4074
E. lmayorga@lm3 <http://lm-3.com/>corp.com
T. @louismayorga

**Comment by lmayorga1980** [comment]
@StefanScherer i would separate the same installer name reference to be a single library but did this in such a rush.

**Comment by StefanScherer** [comment]
@lmayorga1980 still seems good to me for a small PR :-)

**Comment by PatrickLang** [comment]
Sorry I missed this report earlier. We just fixed the installer in #419
