### ISSUE TITLE
hyper-v Containers in Nested VM

### ISSUE THREAD

**Issue by myaesubi** [Microsoft/Virtualization-Documentation#304]
Hi,
I'm running the following command in a Nested VM with TP5 OS and get the error.
Not sure what I miss here as I followed the steps.

docker run -it --isolation=hyperv windowsservercore cmd

Error:
C:\Program Files\Docker\docker.exe: Error response from daemon: container 6223595bbfda3a2244511d790f447f6875679c0c6854915c59810a1beeb4111e enc
ountered an error during CreateContainer failed in Win32: Not enough storage is available to complete this operation. (0xe) extra info: {"Syst
emType":"Container","Name":"6223595bbfda3a2244511d790f447f6875679c0c6854915c59810a1beeb4111e","Owner":"docker","IsDummy":false,"VolumePath":""
,"IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\6223595bbfda3a2244511d790f447f6875679c0c6854915c598
10a1beeb4111e","Layers":[{"ID":"d8d90394-03a9-5513-976b-9923314296d4","Path":"C:\\ProgramData\\Microsoft\\Windows\\Images\\CN=Microsoft_Window
sServerCore_10.0.14300.1000"}],"HostName":"6223595bbfda","MappedDirectories":[],"SandboxPath":"C:\\ProgramData\\docker\\windowsfilter","HvPart
ition":true,"EndpointList":["bf18a91f-8369-42ca-9d97-064f55c2468e"],"HvRuntime":{},"Servicing":false}.

**Comment by neilpeterson** [comment]
When I have seen this in the past, the issue has to do with the host and nested host (vm) not beeing of the same Windows build. 

Check out the prerequisites on this page - https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/nesting. 

You can verify the build on both host and nested host using the following:

```none
powershell [System.Environment]::OSVersion.Version
```

Thanks

neilp

**Comment by myaesubi** [comment]
Thanks Neil,
Correct, my host is Win 10, Nested Host is TP5. thought they would work together.

Mohammad

**Comment by neilpeterson** [comment]
We can nest Windows 10 under Windows server. Can you provide the output of this command for both systems?

```none
powershell [System.Environment]::OSVersion.Version
```

Thanks

**Comment by myaesubi** [comment]
On TP5 VM which is the Nested Hyper-V Host-> 10   0    14300 0
On Win 10 which is the host for TP5 VM->           10   0    10586 0

so my guess is that my case should be other way; having Win 10 VM host on TP5 Physical.

Thanks,
Mohammad

**Comment by neilpeterson** [comment]
@theodthompson for conformation.

Thanks

**Comment by theodthompson** [comment]
I don't think this is nested virtualization related... "Not enough storage is available to complete this operation". Could you check that there is enough storage space for your VM?

**Comment by neilpeterson** [comment]
@theodthompson my assumption was that the error is erroneous. I have worked a few identical support cases where in each case the common configuration has been a nested hypervisors with miss-matched builds.

I can currently reproduce the issue in an environment of identical builds to @myaesubi.

Parent hypervisor:

```none
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      10586  0
``` 

Child hypervisor:

```none
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14300  0
```

```none
PS C:\Users\Administrator> docker run -it --isolation=hyperv nanoserver cmd
C:\Program Files\Docker\docker.exe: Error response from daemon: container 71f3c3f513d56b135bedc2304c915a4460a277c0ff081f7cdca05ef3e0c0f14d encountered an error during CreateContainer failed in Win32: Not enough storage is available to complete this operation. (0xe) extra info: {"SystemType":"Container","Name":"71f3c3f513d56b135bedc2304c915a4460a277c0ff081f7cdca05ef3e0c0f14d","Owner":"docker","IsDummy":false,"VolumePath":"","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\71f3c3f513d56b135bedc2304c915a4460a277c0ff081f7cdca05ef3e0c0f14d","Layers":[{"ID":"5dfff73d-ae84-5f96-bb52-dc902a421811","Path":"C:\\ProgramData\\Microsoft\\Windows\\Images\\CN=Microsoft_NanoServer_10.0.14300.1016"}],"HostName":"71f3c3f513d5","MappedDirectories":[],"SandboxPath":"C:\\ProgramData\\docker\\windowsfilter","HvPartition":true,"EndpointList":["0c32e84c-ebcb-4e03-aa0c-63f90d0bc9c2"],"HvRuntime":{},"Servicing":false}.
```

When trying to start a 'regular' virtual machine, I receive the following:

![6-13-2016 8-33-14 pm](https://cloud.githubusercontent.com/assets/7844635/16030474/288412d6-31a6-11e6-96e2-636929e7c9ab.png)

The virtual machine (child hypervisor) is resourced fine (8GB memory, 30GB disk free, and 2 processors), nested virtualization has been enabled. I can see that the vmms process is running fine.

**Comment by theodthompson** [comment]
@neilpeterson thanks for the explanation. Your instincts are correct in that the Docker error message doesn't really indicate the problem.

The problem is that the hypervisor hasn't started, which can happen for a number of reasons. In this case it is because the builds are incompatible (like you said...).
