### ISSUE TITLE
Nested Viurtualization non-identical parent and child

### ISSUE THREAD

**Issue by KariFinn** [Microsoft/Virtualization-Documentation#306]
According to documentation on https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/user_guide/nesting, both hypervisors (parent and child) must be running identical Windows builds.

OK, that is valid when setting up the child but when done, it apparently can be upgraded to a different build than parent. In screenshot my 14352 Education host (parent) running 14361 Pro guest (child) where I am installing 14361 Pro on Hyper-V.

Screenshot: https://onedrive.live.com/redir?resid=FCDCA7D2E5A3FC02!120940&authkey=!AIWstteDrLHuEkY&v=3&ithint=photo%2cpng

Guest / child was 14352 Pro when nested virtualization was set up and Hyper-V feature installed, hence the vm name in title bar in screenshot, then upgraded to 14361 using ISO created from original 14361 ESD file. Hyper-V on child has no issues even when builds are different.

**Comment by theodthompson** [comment]
Thanks for reporting this! There are times when similar builds will work together, but the only way to know for sure that nesting will work is to run the same build. That's why we advise running the same build # on the parent and child.

-Theo
