### ISSUE TITLE
Deployment_Nano steps are not sequential

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/Virtualization-Documentation#312]
The [Deployment_Nano](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deployment/deployment_nano.md) steps are not sequential.  The [Install Base Container Images](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/deployment/deployment_nano.md#install-base-container-images) section instructs the user to run the `docker tag` command yet the steps have not specified how to install the docker client.  Installing the client for remote management is described later on.  

My suggestion would be to either include the steps for installing the docker client after installing the daemon or to provide a link to the client install steps when giving the `docker tag` command.

**Comment by neilpeterson** [comment]
@MichaelSimons, totally agree. I will look into it.

**Comment by neilpeterson** [comment]
@MichaelSimons topic has been updated such that it can be run sequentially. Thanks for submitting this.

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment_nano
