### ISSUE TITLE
TP5: "HNS failed with error" when mapping the same port for TCP/UDP

### ISSUE THREAD

**Issue by mwieczorek** [Microsoft/Virtualization-Documentation#319]
I run:

```
docker run -d -p 8900:8900/udp -p 8900:8900 windowsservercore:latest ping -t localhost
```

and get an error:

```
C:\Windows\system32\docker.exe: 
Error response from daemon: failed to create endpoint modest_leavitt on network nat: 
HNS failed with error : 
Failed to create endpoint.
```

If I run only with udp or tcp mapping - everything is working fine.
Is it  (opening tcp/udp for the same port)  supported on windows containers?

**Comment by JMesser81** [comment]
This is a known bug with Windows Server 2016 Technical Preview 5. It will be fixed in the next release. Sorry for the inconvenience.

**Comment by mwieczorek** [comment]
Any timeline for new release?

**Comment by Delostik** [comment]
1. use Get-NetNatStaticMapping and Remove-NetNatStaticMapping to unmap port.
2. remove the container which holds the internal port.

**Comment by sitano** [comment]
@Delostik 

> use Get-NetNatStaticMapping and Remove-NetNatStaticMapping to unmap port.
remove the container which holds the internal port.

This would not work. This is not an issue of used/opened/mapped port mapping. It's not working in windows when nat table is empty and there are not containers.

Still not working with: 

**Output of `docker version`:**

```
PS C:\> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   20607e2
 Built:        Wed Sep  7 15:57:02 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   20607e2
 Built:        Wed Sep  7 15:57:02 2016
 OS/Arch:      windows/amd64
```


**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 1
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1052.amd64fre.rs1_release_svc.160721-1818)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 16 GiB
Name: azus103
ID: XU2V:CWCS:HRAV:K3LG:2IRZ:WJYW:7J2J:W4GV:5YL6:JLBX:LZAX:2QYU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Microsoft Azure Cloud

```
PS C:\> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.14300.0 Microsoft Windows NT 10.0.14300.0
```

**Comment by sitano** [comment]
This certain version of Windows / Docker have also another critical issue related to the UDP/TCP bindings on the same port resulting broken packets in outcoming traffic https://github.com/docker/docker/issues/26490

**Comment by godefroi** [comment]
I can confirm that this is an issue in TP5. Attempting to bind the same port with both TCP and UDP fails; remove UDP and bind only TCP, and it works.

**Comment by rs38** [comment]
how does this behave in hyper-v Win10 1607 containers?

**Comment by StefanScherer** [comment]
Works in Server 2016

```
PS C:> docker run -d -p 8900:8900/udp -p 8900:8900 microsoft/windowsservercore ping -t localhost
74c9bbe9a035324d4abd2a398a331618c4372ea4bf13f73b2de9dfca28415c36
PS C:> docker ps
CONTAINER ID        IMAGE                         COMMAND               CREATED             STATUS              PORTS                                            NAMES
74c9bbe9a035        microsoft/windowsservercore   "ping -t localhost"   7 seconds ago       Up 3 seconds        0.0.0.0:8900->8900/tcp, 0.0.0.0:8900->8900/udp   pensive_galileo
```

as well as  on Win 10 1607 with nanoserver

```
PS C:> docker run -d -p 8900:8900/udp -p 8900:8900 microsoft/nanoserver ping -t localhost
```

**Comment by rs38** [comment]
I had similar errors which also showed up as unremovable VSwitch in Hyper-V manager and probably came from previous container tests in earlier stages.
for me this was very helpful:[-> link to container networking]( https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking)

finally this helped (in a similar scenario)
Get-ContainerNetwork | Remove-ContainerNetwork

**Comment by PatrickLang** [comment]
Closing - those doc links look right
