### ISSUE TITLE
Unable to start a nanoserver container on Windows 10 Insider Preview build 14390

### ISSUE THREAD

**Issue by mlapierre** [Microsoft/Virtualization-Documentation#340]
I've followed [the instructions](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10) up until running the container. The command and error are:
```
C:\>docker run -it nanoserver cmd
C:\Program Files\docker\docker.exe: Error response from daemon: container 
4a82b38a3304e43473975941f54dd047bbf0c57ed8e3322d5f819122edf43071 encountered an error during 
Start failed in Win32: The system cannot find the path specified. (0x3).
```
How would I find out what path it's referring to?

I previously had docker running via boot2docker and then Docker for Windows however both have been uninstalled.

**Comment by rs38** [comment]
tried removing old virtual nat switches?
check for remove-containernetworks and also retry with current updates to win10 and conainer engine.

**Comment by mlapierre** [comment]
Yeah, updates since I opened this issue have fixed it. It works now.

I did try removing old virtual nat switches. And all other network-related configuration. Whatever the problem was it's all good now.
