### ISSUE TITLE
Docker pull issue

### ISSUE THREAD

**Issue by ddobric** [Microsoft/Virtualization-Documentation#351]
I have installed VM (Version 10.0.14300) by using ARM template provided here: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_server

When trying to pull any container from repository I get error: "unknown blob".

Here is one example:

docker pull microsoft/sample-node
Using default tag: latest
latest: Pulling from microsoft/sample-node
cf62dbf6d334: Downloading
572944f0bc92: Download complete
unknown blob

**Comment by ddobric** [comment]
Anybody?

**Comment by PatrickLang** [comment]
Can you post `docker images` and `docker version` output? We have been republishing all of the microsoft/* images over the last week so that `docker pull` will automatically download the Windows base OS images (Microsoft/nanoserver, microsoft/windowsservercore) That will help us determine if you're using the old vs new images.

**Comment by ddobric** [comment]
--- images ---
PS C:\Windows\system32> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED
windowsservercore   10.0.14300.1000     5bc36a335344        12 weeks ago
windowsservercore   latest              5bc36a335344        12 weeks ago
nanoserver          10.0.14300.1016     3f5112ddd185        12 weeks ago
nanoserver          latest              3f5112ddd185        12 weeks ago

---- version ---
PS C:\Windows\system32> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   3d80884
 Built:        Mon Jun  6 19:12:50 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   3d80884
 Built:        Mon Jun  6 19:12:50 2016
 OS/Arch:      windows/amd64

**Comment by PatrickLang** [comment]
Ah ok, can you try this?
Start from Step 2 here to update the Docker version, then continue installing the new images afterwards. 
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

**Comment by PatrickLang** [comment]
Alright - I figured out what's up. There is a new image published with the updated Docker daemon and binaries, but the template wasn't using it.

I worked up a quick update and am testing it now. If you'd like to try it, you can deploy using this template:
https://github.com/Microsoft/Virtualization-Documentation/tree/aztemplateupdate/windows-server-container-tools/containers-azure-template

**Comment by PatrickLang** [comment]
I can pull that image now:
```none
PS C:\Users\patrick> docker pull microsoft/sample-node
Using default tag: latest
latest: Pulling from microsoft/sample-node

cf62dbf6d334: Pull complete
572944f0bc92: Pull complete
Digest: sha256:8542b98eaddb5abb217ad288b8a9ac9ff40b1a740f001d9646e8e4df612bd61d
Status: Downloaded newer image for microsoft/sample-node:latest
```

**Comment by ddobric** [comment]
Thanks guys, this worked (with small issues)
I did following at the end:

1. service-stop docker

2. Invoke-WebRequest "https://get.docker.com/builds/Windows/x86_64/docker-1.12.0.zip" -OutFile "$env:TEMP\docker-1.12.0.zip" -UseBasicParsing

3. Expand-Archive -Path "$env:TEMP\docker-1.12.0.zip" -DestinationPath $env:ProgramFiles -Force

4. service-start docker

**Comment by StefanScherer** [comment]
Just created a new Azure VM with the updated `azuredeploy.json`. Works fine. Thanks!
Pulling/running images from Hub also works, eg. `docker run -it stefanscherer/node-windows:4.4.7 node --version`
