### ISSUE TITLE
Are steps from Docker.com same as These?

### ISSUE THREAD

**Issue by cicorias** [Microsoft/Virtualization-Documentation#363]
Given Docker for Windows has been released, it's not clear if their install is the same as the install you identified in this article.  

So, is https://docs.docker.com/docker-for-windows/  which points to https://download.docker.com/win/stable/InstallDocker.msi

Going to get me the same as this one articulated in the article?

```
Invoke-WebRequest "https://master.dockerproject.org/windows/amd64/docker-1.13.0-dev.zip" -OutFile "$env:TEMP\docker-1.13.0-dev.zip" -UseBasicParsing
```

Which is preferred or at least recognize the different paths that might get the same thing.

**Comment by friism** [comment]
@cicorias These install different things:

1. Docker for Windows installs a Docker Linux container development environment on Windows
2. This documentation takes you through installing Docker _Windows_ container engine for running Docker Windows containers

Here's how you can run them side-by-side: https://forums.docker.com/t/linux-and-windows-images-side-by-side/20518/4?u=friism

At Docker, we're working on making Docker for Windows also set up the Docker _Windows_ container engine (in addition to the Linux components)
