### ISSUE TITLE
Docker windows 2016 IIS image push to private linux docker registry fails

### ISSUE THREAD

**Issue by aneezhcl** [Microsoft/Virtualization-Documentation#366]
Dears,
Any helps on the below issue will be highly appreciated .

Error - HTTP error when windows iis image pushing to Linux Repository
### Actual behavior

C:\Windows\system32>docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
webdeploy                     latest              00e5ab98ca2a        14 hours ago        7.982 GB
nginx                         latest              f616c9331369        14 hours ago        7.889 GB
192.168.137.101:7777/iis      latest              03827c9ad22c        14 hours ago        7.901 GB
iis                           latest              03827c9ad22c        14 hours ago        7.901 GB
ane-commit-iis                latest              3d77350d6c70        15 hours ago        7.902 GB
microsoft/iis                 latest              accd044753c1        3 weeks ago         7.907 GB
microsoft/windowsservercore   10.0.14300.1030     02cb7f65d61b        10 weeks ago        7.764 GB
microsoft/windowsservercore   latest              02cb7f65d61b        10 weeks ago        7.764 GB
C:\Windows\system32>
C:\Windows\system32>docker push 192.168.137.101:7777/iis
The push refers to a repository [192.168.137.101:7777/iis]
Get https://192.168.137.101:7777/v1/_ping: http: server gave HTTP response to HTTPS client
### Information

PS C:\Windows\system32> docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64
PS C:\Windows\system32>
## Docker Linux Repository docker host version information

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64
### Steps to reproduce the behavior

docker tag iis 192.168.137.101:7777/iis
docker push 192.168.137.101:7777/iis

**Comment by friism** [comment]
Is it only Windows images that you can't push to that registry? The error might be because you'd haven't setup TLS with your registry, there's a workaround here: http://stackoverflow.com/a/38716311/2942

**Comment by PatrickLang** [comment]
We're not planning on tracking registry issues here, so I'm going to close this out. The [registry](https://hub.docker.com/r/library/registry/) v2 and higher support Windows container images. Issues are tracked at https://github.com/docker/distribution
