### ISSUE TITLE
Docker-Compose?

### ISSUE THREAD

**Issue by gravidThoughts** [Microsoft/Virtualization-Documentation#370]
Appreciated this [Windows Containers on Windows 10 quickstart](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/quick_start_windows_10.md). I was able to get up and runnning quickly.

The problem now, is I want to play with Docker-Compose which is not contained in the zip file used to install Docker in the quickstart guide.

I now have a few questions.

Can I use the [Dockers for Windows Stable 1.12.0](https://docs.docker.com/docker-for-windows/) installer instead, or does Windows 10 Anniversary update require 1.13.0? The nice thing about Dockers for Windows is that it comes with Docker-Compose and  Windows UI apps(notification tray app, configuration etc.).

If I have to use 1.13.0, can I use the Docker-Compose 1.8.0 windows binary located [here](https://github.com/docker/compose/releases) and just drop it into the Docker directory?

Moving forward will maintaining a Docker installation manually in windows, instead of with an installer and windows distribution provided by Docker, be viable?

**Comment by StefanScherer** [comment]
@gravidThoughts Docker for Windows 1.12 is a tool to run Linux containers on Windows 10. Running Windows containers with it is planned for the future.

If you want to run Windows containers you need 1.13.0-dev on Windows 10 AU at the moment.

Downloading Docker-compose from the GitHub release is the way to go, perhaps you use Chocolatey, then `choco install docker-compose` will do the download for you :-)

**Comment by ferrx** [comment]
This info was so hard to find! Thanks

**Comment by PatrickLang** [comment]
Closing - we added a compose sample a few weeks ago. This lab is also excellent:
https://github.com/docker/labs/blob/master/windows/windows-containers/MultiContainerApp.md
