### ISSUE TITLE
Can not use RDP to managed/interacted Windows Containers

### ISSUE THREAD

**Issue by keyilela** [Microsoft/Virtualization-Documentation#377]
Windows Containers can be managed/interacted with through a RDP session

**Comment by xied75** [comment]
It does not support that as of now. 

https://social.msdn.microsoft.com/Forums/en-US/f4314bc8-52d0-477c-9ecc-86a578b53814/no-support-expected-for-rdp-in-containers-for-windows-server-2016?forum=windowscontainers

For questions like this it's better to ask on the Forum, that's Microsoft way. :)

**Comment by neilpeterson** [comment]
Yep, this is not supported, I will close the issue.

**Comment by BerkOzdilek** [comment]
Is it supported now ?
