### ISSUE TITLE
BitLocker error 0xc0210000 after installing Hyper-V on Windows 10 client

### ISSUE THREAD

**Issue by gavinbarron** [Microsoft/Virtualization-Documentation#392]
I was following the Windows 10 Quick Start and encounted the above issue.
There's a thread on MSDN/TechNet on this issues https://social.technet.microsoft.com/Forums/en-US/1a937e9e-19ab-42c6-b314-ecce189c0a08/bitlocker-error-0xc0210000-after-installing-hyperv-on-windows-10-client?forum=mdopmbam

I think the docs need guidance to help people avoid this issue

**Comment by neilpeterson** [comment]
Cc. @scooley

**Comment by neilpeterson** [comment]
PR - https://github.com/Microsoft/Virtualization-Documentation/pull/393

**Comment by PatrickLang** [comment]
This was fixed in Windows updates, and clarified in the docs. Closing
