### ISSUE TITLE
Container Host - Nano Server documentation should use Invoke-WebRequest on Nano Server

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/Virtualization-Documentation#394]
The _Container host deployment - Nano Server_ documentation says

> Nano Server does not currently support Invoke-WebRequest. the download will need to be completed on a remote system, and the files copied to the Nano Server host.

It appears that the latest version of Nano Server now supports the Invoke-WebRequest cmdlet.  The documentation should make use of this as it would make the setup steps simpler.  Downloading on a remote system and coping the contents to the Nano Server is a pain.

@neilpeterson

**Comment by neilpeterson** [comment]
@MichaelSimons thanks. Can you reply with the OS Version of you Nano instance? I am not seeing the command on mine.

```none
[environment]::OSVersion.Version
```

Thanks

neilp

**Comment by MichaelSimons** [comment]
@neilpeterson 

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

**Comment by neilpeterson** [comment]
Got it, applied updates, and there it is. I will get this updated ASAP.

Thanks again.

neilp

**Comment by friism** [comment]
> It appears that the latest version of Nano Server now supports the Invoke-WebRequest cmdlet

Hallelujah!

**Comment by neilpeterson** [comment]
Doc has been updated, thanks again for raising the issue.

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment_nano

**Comment by StefanScherer** [comment]
@MichaelSimons Wow, that are good news! Shrinking a file download in a Nanoserver Dockerfile from [11 lines of code](https://github.com/Microsoft/Virtualization-Documentation/blob/df9723e3a9d9ada778d01d43dcb36c99813dea8f/windows-container-samples/nanoserver/golang/Dockerfile#L10-L20) into a single line again! 💯

**Comment by DarwinJS** [comment]
@friism - when I do "get-command invoke-webrequest" on a freshly booted Nano RTM box (with no extras installed) I get "...not recognized as the name of a cmdlet..." - is there a nano package install required to have invoke-webrequest?

**Comment by MichaelSimons** [comment]
@DarwinJS - Have you installed the available updates on this machine?  This may be a requirement.

**Comment by DarwinJS** [comment]
Good point.  I have not.  However, I also do not want to.

This is for the script I have created that allows automated install for anyone to use - so I don't want to force any updates or optional components onto their Nano build just to get an install done.  

Also when people just want to try the automated install, they probably won't install updates for a quick kick the tires and then assume it does not work.

My current method (using package management NuGet provider) does not require the updates to be run - so I will stick with it.

Here is the repo with the files and a Dockerfile for getting Win32-OpenSSH installed on *bare* Nano RTM: https://github.com/DarwinJS/ChocoPackages/tree/master/openssh
