### ISSUE TITLE
Deploy first container fails

### ISSUE THREAD

**Issue by bilberry79** [Microsoft/Virtualization-Documentation#395]
Hi,

I followed the instructions as described here:
(https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)
from step 1. to step 4. Deploy Your First Container without any problems.

If I try to run: `docker run -it microsoft/nanoserver cmd`
A svchost.exe process starts and constantly consumes 25% CPU and nothing happens. The container doesn't start.

Any ideas?

Best,
Matthias

**Comment by jhowardmsft** [comment]
Yes known. There is an update due out tomorrow I believe. Run Windows Update and life should be good after. It'll be a big one, some 800MB. Sorry, don't have KB number though yet.

**Comment by bilberry79** [comment]
Great. Thanks for the quick reply. I'll wait then.

**Comment by StefanScherer** [comment]
As mentioned in #358, there is a Windows Update KB3194496 for Windows 10 which should fix that. Just trying this myself.

**Comment by StefanScherer** [comment]
Yes, it works after installing the update KB3194496.

**Comment by bilberry79** [comment]
I can confirm this. It works after installing update KB3194496.
