### ISSUE TITLE
Can not run a nano server container on Windows10(Build14936);Info:The JSON document is invalid. (0xc037010d).

### ISSUE THREAD

**Issue by GreatVincy** [Microsoft/Virtualization-Documentation#398]
When I try to run the nano server container on Windows10 with command below in the PowerShell,an error occured.
【docker run -it microsoft/nanoserver cmd】
【C:\Program Files\Docker\docker.exe: Error response from daemon: container 9f2b64b04eac871767cd4014352ca921824676def806b4
14a0c9570b0a5c3076 encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d)】
I have tried several times,but it did not work.What should I do?Please help me,thanks!

**Comment by StefanScherer** [comment]
What is the output of `docker version` and `docker info`?
Do you have all Windows updates installed, especially KB3194496?

**Comment by GreatVincy** [comment]
Thank you for your answer！
docker info:
![info](https://cloud.githubusercontent.com/assets/17567321/19014237/3ddc877e-881a-11e6-9de5-a22488edb172.PNG)
docker version:
![version](https://cloud.githubusercontent.com/assets/17567321/19014238/3ddd5f8c-881a-11e6-9f6f-50fb0dac977c.PNG)
I think I have installed KB3194496,because my OS version is  newer than _Version1607_ .It is a _InsiderPreview_ version.Is it the bug of this version?
![osdetail](https://cloud.githubusercontent.com/assets/17567321/19014283/d66fa038-881b-11e6-8b99-d681e0863901.PNG)
![osversion](https://cloud.githubusercontent.com/assets/17567321/19014282/d66f4fc0-881b-11e6-9947-94d5b357d4bf.PNG)
And there is the error message:
![error](https://cloud.githubusercontent.com/assets/17567321/19014318/cda90056-881c-11e6-8ec1-6330fd6968ca.PNG)

**Comment by FeodorFitsner** [comment]
Getting the same error since today's morning while running `docker run -it microsoft/windowsservercore cmd`:

```
PS C:\WINDOWS\system32> docker run microsoft/windowsservercore cmd
C:\Program Files\Docker\docker.exe: Error response from daemon: container e493d0e5490b1e714c94e89907ff5268b1aa2677d58305
19ca6220c4cf9e3b0a encountered an error during Start failed in Win32: The JSON document is invalid. (0xc037010d).
```

Looks like something's broken in the latest Windows 10 update. I'm on `Version 1607 (OS Build 14936.1000)`.

**Comment by WouterDeKort** [comment]
Is there some fix or workaround for this? I'm still running into the same issue.

**Comment by jhowardmsft** [comment]
@PatrickLang Sounds like something is broken on the latest insider flight in HCS incompatibility with the daemon. Is this known and being tracked internally?

**Comment by PatrickLang** [comment]
Yes, this is a known problem on 14931 and 14936. This should be fixed in a future Windows Insider build. I see Windows Insider - Fast has a newer build, so I'm asking if that fixes it. I'll post back when I know more.

**Comment by PatrickLang** [comment]
Closing - known issue on older builds.
