### ISSUE TITLE
part of first steps in Windows Containers on Windows Server missing

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#399]
Virtualization-Documentation/virtualization/windowscontainers/quick_start/quick_start_windows_server.md

where is the part gone that shows how to pull the image(s) from docker?

**Comment by neilpeterson** [comment]
When running ‘docker run’ an image will be pulled if not already present. For this quick tutorial, ‘docker pull’ pull is not necessary. 

This one goes a bit more into images, and includes push and pull:

[Container Images on Windows Server](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_images)

Here is the in-depth documentation for images on [docs.docker.com](https://docs.docker.com/engine/tutorials/dockerimages/).

Does this address the issue?

Thanks

neilp

**Comment by rs38** [comment]
simply compare the same section in the windows 10 topic. That's more straight forward there....
For you, who deals with it everyday it may not be so obvious.
I left focussing on windows container after tp3 or tp4 and come back I initially I do not get much of it :) 
e.g. what happened to the powershell interface to containers like start-container etc.? there is no side by side docker and powershell regarding containers I guess?

**Comment by rs38** [comment]
next issue I get when being confused whether to install latest docker for windows beta as suggested by @StefanScherer (which seems to be server version 1.12) or if I stick on getting it with the 1.13dev like in the docs. neither way currently runs on my Win10 machine

**Comment by rs38** [comment]
after all I need to apologise: I wasn't aware that docker run also pulls sth. I could not try more because auf troubling with latest Win10 Fix and/or find out which version of docker is right for me. also I got stuck with an older virtula nat switch which blocked me until I found out to remove it with ver_ContainerNetzworks commandlets.

**Comment by neilpeterson** [comment]
@rs38 no apologies necessary, your initial feedback is very valid. I will look into adding some clarifying text around docker run as it pertains to pulling images.

Thanks

neilp
