### ISSUE TITLE
Windows 10 Container Tutorial adds Docker twice to system path

### ISSUE THREAD

**Issue by jouniheikniemi** [Microsoft/Virtualization-Documentation#411]
In https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick_start/quick_start_windows_10.md, you're adding Docker to the system path twice. First you're updating $env:Path, then you're setting the path again with catenation of the Docker path at the end.

Also, would perhaps be better practice to get the system version of the path variable when setting it; now you're also storing all other possible process-level path changes into the system path with this "installation script".

**Comment by neilpeterson** [comment]
I believe all of these steps (installation and configuration) will soon be updated with a much more simple process.

@enderb-ms , @taylorb-microsoft for progress on the Docker package provider.

Thanks

**Comment by dongyuzheng** [comment]
The first one is to set the path for the current shell, which will not persist when you open new shells.
The second one is for the path to be set when you open new shells - which doesn't affect the current one you're working on.

**Comment by arun-gupta** [comment]
Really hoping the process is simplified. The steps listed at https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server?f=255&MSPPError=-2147217396 are quite daunting. Not sure how many first time users will drop out because of this.

**Comment by friism** [comment]
@arun-gupta https://github.com/Microsoft/Virtualization-Documentation/pull/423 :-)

**Comment by PatrickLang** [comment]
The current steps make a change in the current PowerShell session, and also apply it to the system. This prevents the need to start a fresh PowerShell session or logout for it to take effect.

```
# For quick use, does not require shell to be restarted.
$env:path += ";c:\program files\docker"

# For persistent use, will apply even after a reboot.
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Docker", [EnvironmentVariableTarget]::Machine)
```

**Comment by jouniheikniemi** [comment]
At least @dongyuzheng and @PatrickLang seem to have misread my original report. I wasn't complaining about why there are two separate path additions - that is obvious and necessary. 

My original point still stands: The system environment path gets Docker directory added twice (i.e. my path ends with "c:\program files\Docker;c:\program files\Docker" which is both ugly and harmful from a perf standpoint. It does work though.

The obvious fix is just to set the system path to $env:Path, since the Docker directory was added to it already in the previous line.

**Comment by jouniheikniemi** [comment]
On second thought, I would like to point out that my secondary comment of getting the system path before setting it also has merit, and hence my "obvious fix" is probably the wrong thing to do. The current approach can accidentally hoist other process-level path changes to system configuration. The user isn't probably intending to commit those to permanent use.

**Comment by PatrickLang** [comment]
Oh yes, you're right. I misread that. I'll fix it. Thanks!

**Comment by PatrickLang** [comment]
PR created and open for review

**Comment by PatrickLang** [comment]
Alright, just merged fix. It's on its way through the publishing pipeline.
