### ISSUE TITLE
//./pipe/docker_engine: Access is denied - after following Windows 10 guide

### ISSUE THREAD

**Issue by jonstelly** [Microsoft/Virtualization-Documentation#412]
I've followed the [Windows Containers on Windows 10 quick-start](https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/quick_start_windows_10) on 3 different machines and at the end I always end up with the same result...

> docker ps
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/json: open //./pipe/docker_engine: Access is denied.```

It's Windows 10 Build 14931, but I had tried it a week or two ago on a previous Windows build with the same result.

If I create a %programdata%/Docker/config/daemon.json with:

> { "hosts": ["tcp://127.0.0.1:2375"] }

and set DOCKER_HOST accordingly then things seem to work fine.

**Comment by jhowardmsft** [comment]
Do you get access denied if you run the client elevated (running on a named pipe, not TCP)

**Comment by jonstelly** [comment]
Odd, I had definitely tried that several times last week (might have been against docker 1.12?) and it didn't work but it's working now if I run as elevated.

Thanks for the quick help, I should have tried that again.

**Comment by jhowardmsft** [comment]
By default, the named pipe is only accessible to administrators. There's no ACLing on TCP ports, anyone can access them regardless of elevation. You can control the named pipe behaviour to allow users to access the pipe using the `-G` parameter to dockerd (or updating the `daemon.json` similarly).

@neilpeterson Is ^^ documented somewhere?

**Comment by killnine** [comment]
@jhowardmsft Sorry, but I'm not understanding how to control named pipe behavior. Is setting behavior an OS-level thing or something specific within daemon.json? 

I am trying to give our TeamCity agent access to the docker daemon running locally on the box.

**Comment by tanushshukla** [comment]
@killnine, did you find anything on this? We are doing the exact same thing. getting this error from TeamCity or anytime we run docker from a non-elevated command prompt.

**Comment by killnine** [comment]
@tanushshukla Unfortunately we have not resolved the issue.  I’ve been pulled off to another task but my next step was going to be uninstalling and reinstalling docker entirely from the host
