### ISSUE TITLE
cannot use docker on remote WinRM Powershell session

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#413]
```
Enter-PSSession -computername 10.xx.xx.xx -credential Administrator
PS C:\Users\Administrator\Documents> docker run -it nanoserver cmd

```
error: **docker : the input device is not a TTY.**

remoted to server 2016 RTM trial. docker client and server is 1.12 beta rc1.
it does not matter if run in ISE or normale ps host.

**Comment by jhowardmsft** [comment]
Fully expected. Poweshell remoting does not expose a (fake as there's not really any such thing as a tty on Windows) tty. To interact -it that way from docker client, connect the client remotely using -H or set DOCKER_HOST. Alternately run single commands as opposed
to cmd and don't use -it from inside the remote session.

**Comment by rs38** [comment]
@jhowardmsft Are this similar reasons why I cannot nest PS remoting?

**Comment by jhowardmsft** [comment]
I don't know. Not my area.

**Comment by rs38** [comment]
but this all means, when hosting my Nanoserver with Docker in Azure the only way to control Docker from outside Azure, I need to expose the unsecured Port 2375 to the world and everyone can take over my docker deamon?

**Comment by jhowardmsft** [comment]
2376 and TLS?

**Comment by rs38** [comment]
will have a view on it. thx!

**Comment by friism** [comment]
I don't understand this problemspace well, but would the powershell for Docker commandlets work better? https://github.com/Microsoft/Docker-PowerShell

**Comment by jhowardmsft** [comment]
@friism Not really as these use the docker.exe client under the covers.

**Comment by friism** [comment]
@jhowardmsft I don't think that's the case. The commandlets call the dockerd HTTP rest API, if I'm not mistaken.

**Comment by jhowardmsft** [comment]
Ah yes, sorry thinking of something else which does wrap the client.

**Comment by jhowardmsft** [comment]
That said, it's still the same problem...

**Comment by PatrickLang** [comment]
Docker-PowerShell should work. It has console redirection code in there.

**Comment by rs38** [comment]
@PatrickLang when I am remoting to a nanoserver, I need to install DockerPS module on it?
It comlains about a JSON dependency missing, so I cannot try out right now

**Comment by rs38** [comment]
Docker-Powershell does not work neither:

@PatrickLang 
`Get-Container | Attach-Container`

Attach-Container : The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
    + CategoryInfo          : NotSpecified: (:) [Enter-ContainerSession], COMException
    + FullyQualifiedErrorId : Docker Client Exception,Docker.PowerShell.Cmdlets.EnterContainerSession
 
Attach-Container : The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
    + CategoryInfo          : NotSpecified: (:) [Enter-ContainerSession], COMException
    + FullyQualifiedErrorId : Docker Client Exception,Docker.PowerShell.Cmdlets.EnterContainerSession
