### ISSUE TITLE
Is it possible to install .NET 4.5 in the docker container ?

### ISSUE THREAD

**Issue by donnib** [Microsoft/Virtualization-Documentation#428]
Hi,
Simmilar to the sample where .NET 3.5 is installed in the container can i install .NET 4.5 ? I am intersted in building .NET 4.5 apps inside a windows docker container for CI purposes.

/donnib

**Comment by friism** [comment]
Yes, there's a good example here: https://github.com/alexellis/aspnet-voteservice

Dockerfiles:

 * https://github.com/alexellis/aspnet-voteservice/blob/master/src/Dockerfile.build
 * https://github.com/alexellis/aspnet-voteservice/blob/master/src/Dockerfile

**Comment by donnib** [comment]
Sorry if i misunderstand. What i want is to be able to build a normal WPF .NET application inside a docker container. The link you sent talks about ASP.Net. Will that work for the above mentioned example ?

**Comment by friism** [comment]
GUI apps are not supported with Windows containers.

**Comment by donnib** [comment]
@friism I know that, i don't need to launch them but build them essentially what i want to do is use a container as a build machine.

**Comment by PatrickLang** [comment]
like this? http://blog.alexellis.io/3-steps-to-msbuild-with-docker/

**Comment by PatrickLang** [comment]
I'm going to close this since there's not a specific issue that we need to fix. I hope those links help, and we're always open to PR's with new samples on this site and also at https://github.com/docker/labs
