### ISSUE TITLE
Docker for Windows Server 2016 requires update KB3176936

### ISSUE THREAD

**Issue by elohmeier** [Microsoft/Virtualization-Documentation#433]
I want to install Docker on a physical Windows Server 2016 Datacenter Evaluation (Version 14393). I tried following the instructions from [Quick Start Windows Server][1] but installation fails:
[Error message][2]

The docker installer requires update KB3176936, which I installed then. Even after rebooting, the error message persists and I can't install docker.

I've enabled the Container feature and Hyper-V in Windows Feature Selection.

Any ideas what I'm doing wrong? I've could sucessfully setup docker on Windows 10.

  [1]: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
  [2]: https://i.stack.imgur.com/TxIIO.png

[also posted here on stackoverflow](http://stackoverflow.com/questions/40154582/docker-for-windows-server-2016-requires-update-kb3176936)

**Comment by elohmeier** [comment]
Solved! Requires an update.
http://stackoverflow.com/questions/40154582/docker-for-windows-server-2016-requires-update-kb3176936

There is a [pull request](https://github.com/Microsoft/Virtualization-Documentation/pull/390/) targeting this issue on github.

**Comment by doggy8088** [comment]
I think this `Windows Updates` section should move to the first section.
