### ISSUE TITLE
cannot get container listening as expected

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#435]
I tried it on Win10 and also native (no VM) server2016 Eval.
disabled firewall and recreated NAT, VMSwitch, container networks.
Also I am aware of that bug(?) that localhost is not working.
But right now I can ONLY connect from a different computer. which luckily can be a VM.

what am I missing?

nothing that is mentioning the caveeats here:
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_images

reproduce:

`docker run -d -p 80:5000 web-app:nanoserver`
eb51234185ad86740e12517cd28e812e3529cc64ec0e12720b045ef8b8f2b476

`docker ps`

```
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                  NAMES
5eb5146185ad        web-app:nanoserver   "dotnet WebApp.d..."   4 minutes ago       Up 4 minutes        0.0.0.0:80->5000/tcp   funny_name
```

`Test-NetConnection $(docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" $(docker ps -q)) -Port 80`
```
WARNING: TCP connect to 172.23.150.200:80 failed
ComputerName           : 172.23.150.200
RemoteAddress          : 172.23.150.200
RemotePort             : 80
InterfaceAlias         : vEthernet (HNS Internal NIC)
SourceAddress          : 172.23.144.1
PingSucceeded          : True
PingReplyDetails (RTT) : 0 ms
TcpTestSucceeded       : False
```

**Comment by StefanScherer** [comment]
@rs38 Have a look at @sixeyed's blog post https://blog.sixeyed.com/published-ports-on-windows-containers-dont-do-loopback/

And use same port on host as in container, that might help.

**Comment by rs38** [comment]
I had a look before. was even trying some of his Dockerfiles.
using same port did not help also. very weird, but I do not completely understand all pitfalls regarding explained in https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/container_networking
yet

**Comment by StefanScherer** [comment]
Ok, just tried `docker run -p 5000:80 microsoft/iis` and can access IIS from outside the Win2016 machine on port 5000 and from within the Win2016 machine using the container's IP and port 80.
So using different host:container port mapping works.

Can you see if your web server is running inside the container and listening to 0.0.0.0:80?

```

C:\> docker ps
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS                  NAMES
26d1c75ecb8e        microsoft/iis       "C:\\ServiceMonitor..."   8 minutes ago       Up 8 minutes        0.0.0.0:5000->80/tcp   gigantic_ptolemy

C:\> docker exec 26d1c netstat -an

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
```

**Comment by rs38** [comment]
of course it does, otherwise I could not reach it from other computers.
here is the output.

```
 docker ps

CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS                  NAMES
e8fdf7494a22        microsoft/iis       "C:\\ServiceMonitor..."   6 minutes ago       Up 6 minutes        0.0.0.0:5000->80/tcp   sharp_aryabhata
PS C:\WINDOWS\system32> docker exec e8fd netstat -an

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:80             0.0.0.0:0              LISTENING
  (.........)
```

thanks for the tip with either EXEC and first digits of the ID, did not know that tricks before.

**Comment by rs38** [comment]
ahhhhhhhhhhhhh....

I cannot believe I mixed up that with local and container port mapping. Now I understand your suggestion to take the same port.

You can easily see my mistake in the first post. I mapped it with docker run -d -p 80:5000 and was testing on port 80 on the inside of the container.

big sorry and thank you.
