### ISSUE TITLE
Cannot run Nanoserver container on Windows Insider Preview (10.0.14931.1000)

### ISSUE THREAD

**Issue by ericwj** [Microsoft/Virtualization-Documentation#436]
Running `docker run -it microsoft/nanoserver cmd` on Windows Insider Preview (10.0.14931.1000):

`C:\program files\docker\docker.exe: Error response from daemon: container b807f2(...) encountered an error during CreateContainer: failure in a Windows system call: The system cannot find the path specified. (0x3) extra info: {(...)}: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.`

I found there are also problems in Hyper-V that might be related. Trying to start a Windows VM 'VM' inside the same VM called 'VS', it'll complain about the VmBus: 

`'VM' failed to start.`

`Microsoft VmBus (Instance ID ...): Failed to Power on with Error 'The system cannot find the path specified.'.`

Virtualization extensions are enabled:

`Get-VMProcessor -VMName VS | select ExposeVirtualizationExtensions`
`ExposeVirtualizationExtensions`
`------------------------------`
`                          True`

The same procedure (following the Windows 10 Quick Start article) works on another virtual machine running Windows 10.0.14393.321. The hardware is also running 10.0.14393.321.

**Comment by PatrickLang** [comment]
Sorry about the trouble here. Builds 14931 and 14936 have bugs and can't run containers. This will be fixed in a future Windows Insider build.

**Comment by ericwj** [comment]
Thanks for the response
