### ISSUE TITLE
What is the equivalent of /var/run/docker.sock in Windows container?

### ISSUE THREAD

**Issue by liiujinfu** [Microsoft/Virtualization-Documentation#442]
I'm intend to capture all commands from docker, so that I can do service discovery, like [registrator](https://github.com/gliderlabs/registrator), for windows, it's may be not a right way, so how can I do like that, any ideas?
thanks

**Comment by friism** [comment]
Docs here: https://docs.docker.com/docker-for-windows/faqs/#/how-do-i-connect-to-the-remote-docker-engine-api

> clients can connect to the Docker Engine through a named pipe: `npipe:////./pipe/docker_engine`

**Comment by StefanScherer** [comment]
Just out of curiosity. I know that `docker run -v npipe:////./pipe/docker_engine:npipe:////./pipe/docker_engine ...` does not work right now. But would it be possible to hand over the named pipe into a container?

**Comment by jhowardmsft** [comment]
No, not possible in the platform. Windows isn't 'file based' in the same way that Linux is.

**Comment by friism** [comment]
@StefanScherer if you make the daemon listen on TCP, you can access it through the container default gateway: http://i-py.com/docker-on-windows-2016-container-introspection-via-docker-daemon-api/

It'd be a cool demo if you could combine this with your SSL work.

**Comment by PatrickLang** [comment]
Yeah, TCP (with or without SSL) is the only way to access a Docker Engine from a Windows container. I looked briefly at registrator, and it looks like it does read DOCKER_HOST.

I'm closing this out since it's not tracking a specific doc issue. We're always happy to take PRs though if you want to add samples later at this repo or at https://github.com/docker/labs

**Comment by ryudice** [comment]
Hi, just wondering what would be the "docker run" command then, given that trying to mount the npipe doesnt work?

**Comment by carlfischer1** [comment]
@ryudice see https://stackoverflow.com/questions/47801477/can-i-use-named-pipes-inside-containers

**Comment by psimoneau22** [comment]
I am not sure what is actually happening beneath the scenes, but the documents for Jenkins container on windows just uses it and it seems to work.  https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/#on-windows

**Comment by emertron01** [comment]
try:
    environment:
        - COMPOSE_CONVERT_WINDOWS_PATHS=1
