### ISSUE TITLE
error pulling image configuration

### ISSUE THREAD

**Issue by eliassal** [Microsoft/Virtualization-Documentation#455]
I have a fresh new win2K16 with containers enabled as well as hyper-v is turned on. Whenever I tru to issue the tes cmmand as indicated to test (firewal disabled, no proxy.....)
docker pull microsoft/windowsservercore:10.0.14393.321

I get

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
93/93a9c37b36d03323f7b8fdd7f0302f7e487a0e8b31ccd8e689c40a404d2f1ea9/data?Expires=1477932342&Signature=N2NdygkaXM6YfVCvXm
TpzD1vDn6k-P50sruyKW21-iVgVdMNwwLUGS0vN2E2ocHrBXowghRgtWX214AcQ5TWo7AqfufXTf~sMU9s3TLQV8ed9-dFAXjC5QMImgTmC8Ef0NsQ26s6~E
tgiWxvm6XJqV8txihfUO46BOuN-n3Lyfs_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 52.85.221.56:443: i/o timeout

Thanks

**Comment by PatrickLang** [comment]
I'm sorry you're having difficulties, but can you open an issue at https://github.com/docker/docker/issues ? That is the best place to track problems with the Docker engine used to manage containers including `docker pull`. This repo is used for documentation and samples only.

**Comment by eliassal** [comment]
OK Patrick, I did, here is the link
https://github.com/docker/docker/issues/27911
