### ISSUE TITLE
Convert-WindowsImage

### ISSUE THREAD

**Issue by mud5150** [Microsoft/Virtualization-Documentation#483]
The readme [here](https://github.com/Microsoft/Virtualization-Documentation/tree/master/hyperv-tools/Convert-WindowsImage) says this code is going to be moved to its own repo. The link to the new repo doesn't work and I'm not getting any response from the email address listed. Is this going to be moved? I'd like to be able to put in a pull request but wasn't sure what the plan is for this code.

**Comment by kallie-b** [comment]
@mebersol -- Do you know who might be able to get this link fixed up?

**Comment by dotps1** [comment]
HELLLLLLLLLLLLLLLLLLLLOOOOOOOOOOOOOOOOOOOOO  this has been broke for a few months now.  Anyone have any idea when this is going to be fixed?  is this project just abandoned?

**Comment by kallie-b** [comment]
Checking on this.

**Comment by mebersol** [comment]
The development effort on this private repo has stalled - I haven't heard from the developer in weeks.  @mud5150 - feel free to submit your PR to this repo for now, Artem can mirror the change when he gets back to the separate repo.

**Comment by mud5150** [comment]
@mebersol Thanks for letting me know.

**Comment by StefanScherer** [comment]
FYI: There is a project https://github.com/docker/communitytools-image2docker-win
