### ISSUE TITLE
Error when using Nano Server Image Builder

### ISSUE THREAD

**Issue by InkUisitor** [Microsoft/Virtualization-Documentation#493]
Hello,
I don't know if it's the good place to talk about that program but I have a problem when I use this program in order to build a vhd for nanoserver. When I use the region French (France), i got the problem. Everything is right when I try with English (United States).
You will find the report created after the failure in attached.
[Report.wer](https://github.com/Microsoft/Virtualization-Documentation/files/603182/Report.txt)

**Comment by PatrickLang** [comment]
Thanks for reporting - it looks like they're tracking problems with that tool [here on uservoice](https://windowsserver.uservoice.com/forums/295068-nano-server). Can you open an issue there? I don't think there is anything we can do in the documentation to work around this problem.

**Comment by InkUisitor** [comment]
@PatrickLang Thanks for the link ;)
