### ISSUE TITLE
svchost runs high CPU and never completes

### ISSUE THREAD

**Issue by paul-green** [Microsoft/Virtualization-Documentation#498]
Hello,

I have Windows Server 2016 - Build 14393.rs1_release 160715-1616 running as a Hyper V machine.

I've installed docker version 14;
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   e308f6b
 Built:        Tue Nov 22 18:15:55 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          e308f6b
 Built:               Tue Nov 22 18:15:55 2016
 OS/Arch:             windows/amd64
 Experimental:        false

And enabled the Containers role, and rebooted.

Whenever I try to perform any 'docker run' command, I get a svchost.exe in the Task List running at close to 100%, the command never returns (waited 30 mins) and I have to kill the process. The same happens with 'docker build' using the samples in Virtualization-Documentation.

Even the simplest 'echo hello' doesn't work.

I had to manually download and run the MSU to install KB3176936 and KB3182137 before docker would install as Windows reported there were no applicable updates.

I'm a bit stumped but it seems to me this process shouldn't be running so hot.

Many thanks
Paul Green.

**Comment by friism** [comment]
@paul-green did you figure out what the problem was?

**Comment by paul-green** [comment]
For some reason I had to manually install KB3200970 (http://www.catalog.update.microsoft.com/Search.aspx?q=KB3200970) to fix the issue. Neither sconfig/6/A nor using the Windows Update UI would detect that updates were needed.

**Comment by paul-green** [comment]
....And the reason for that is (I just found out via some nifty registry monitoring) is that the place I work for has it's own Windows Update server - which hasn't got any of the updates for Server 2016 on it! D. O. H.!
