### ISSUE TITLE
Convert-WindowsImage fail on win10

### ISSUE THREAD

**Issue by BladeFireLight** [Microsoft/Virtualization-Documentation#50]
If Microsoft-Hyper-V-Management-PowerShell is enabled but Microsoft-Hyper-V-Services is disabled. Convert-WindowsImage incorrectly assumes that New-VHD is going to work.

**Comment by mebersol** [comment]
Totally a bug.

**Comment by mebersol** [comment]
Fixed on 12/13

**Comment by mebersol** [comment]
https://github.com/Microsoft/Virtualization-Documentation/commit/3225e29754bc0c74a4e3f83048de7c1171326e22
