### ISSUE TITLE
How to install software base on microsoft/windowsservercore

### ISSUE THREAD

**Issue by renerchen** [Microsoft/Virtualization-Documentation#508]
I want to build a docker image base on microsoft/windowsservercore with installing some software.  Fistly I run docker command :
 docker run -ti microsoft/windowsservercore cmd
then I enter container and execute xxx.exe, it doesn't work. 
why?

**Comment by StefanScherer** [comment]
Do you have a `Dockerfile` to share? Something like

```Dockerfile
FROM microsoft/windowsservercore
COPY myapp.exe /myapp.exe
CMD ["C:\\myapp.exe"]
```

**Comment by PatrickLang** [comment]
@renerchen have you looked at the samples in this repo such as https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-container-samples/python ?

**Comment by renerchen** [comment]
@PatrickLang I had read the windows-container-samples. For example, the python Dockerfile is:

FROM microsoft/windowsservercore
LABEL Description="Python" Vendor="Python Software Foundation" Version="3.5.1"
RUN powershell.exe -Command \
    $ErrorActionPreference = 'Stop'; \
    wget https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \
    Start-Process c:\python-3.5.1.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
    Remove-Item c:\python-3.5.1.exe -Force
RUN echo print("Hello World!") > c:\hello.py
CMD ["py", "c:/hello.py"]

From the python example, python is installed using commands without UI.  If I want to install other software, I must found the installation commands without UI.  But some software doesn't have installation commands without UI, then, I don't know how to install them. Do you have methods?

**Comment by friism** [comment]
@renerchen if the software doesn't have a silent or quiet way to install, it's probably going to be hard to install in a Dockerfile.

For inspiration on whether a particular piece of software has quiet installer, Chocolatey is a great resource: https://chocolatey.org/

**Comment by StefanScherer** [comment]
@renerchen You are lucky as there already is an official python Docker image for Windows. So you don't have to care about how to install such runtime Have a look at https://hub.docker.com/_/python/ and there at all the windowsservercore (and maybe nanoserver) tags.

So your example would look like

```
FROM python:3.5.2-windowsservercore
COPY hello.py c:\hello.py
CMD ["python", "c:\\hello.py"]
```

You can manage your Python sources on your host to put it into source control and COPY deploy it into the docker image.

```
$ docker build -t python-example .
Sending build context to Docker daemon 3.072 kB
Step 1/3 : FROM python:3.5.2-windowsservercore
3.5.2-windowsservercore: Pulling from library/python
9c7f9c7d9bc2: Already exists 
d33fff6043a1: Already exists 
f24cd6bb1240: Pull complete 
93d3d20b02aa: Pull complete 
87b7340a4ad4: Pull complete 
752ccf7f6f94: Pull complete 
71c8687f0163: Pull complete 
98e3a52108d3: Pull complete 
Digest: sha256:f18c60bc38f0ee27e1e066b135f1c9d75d1e331df20967e1992fa13f24c26642
Status: Downloaded newer image for python:3.5.2-windowsservercore
 ---> 6585c54a0693
Step 2/3 : COPY hello.py c:\hello.py
 ---> 1fd240f9a169
Removing intermediate container 28f1bf52fa2a
Step 3/3 : CMD python c:\hello.py
 ---> Running in b8892b9354d5
 ---> 1a08dfc8e98f
Removing intermediate container b8892b9354d5
Successfully built 1a08dfc8e98f

$ docker run python-example
Hello Windows container
```
