### ISSUE TITLE
Friendly, pronounceable names for Windows Server Containers

### ISSUE THREAD

**Issue by dustinkirkland** [Microsoft/Virtualization-Documentation#51]
It has become a somewhat common practice to provide unique, friendly "names" to containers.  It's quite nice when talking about a container in conversation, over the phone, or in code.

One really nice, extensible, secure way of doing so is using the "petname" project [1].  You could easily embed petname in Windows Server Containers!

Petname libraries (and standalone binaries) currently exist in Python [2], Golang [3], and Shell [4] -- all licensed under Apache 2 -- so take your pick!

[1] http://blog.dustinkirkland.com/2015/01/introducing-petname-libraries-for.html
[2] https://github.com/dustinkirkland/python-petname
[3] https://github.com/dustinkirkland/golang-petname
[4] https://github.com/dustinkirkland/petname

**Comment by StefanScherer** [comment]
Docker uses this [names-generator.go](https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go). It seems that there is missing some Windows porting effort as line 444 handles only "foreign" operating systems ;-)

**Comment by dustinkirkland** [comment]
Docker's names-generator.go is okay.  Instead, I was suggesting a different
approach:
https://github.com/dustinkirkland/golang-petname/blob/master/petname.go
