### ISSUE TITLE
Proposal: Shorter link to Debug-ContainerHost.ps1 script

### ISSUE THREAD

**Issue by StefanScherer** [Microsoft/Virtualization-Documentation#525]
Just an idea as I can't remember the whole link to the `Debug-ContainerHost.ps1` script. What about a shorter link that forwards to the GitHub download link?

```
Invoke-WebRequest https://aka.ms/Debug-ContainerHost.ps1 -UseBasicParsing | Invoke-Expression
```

Preview:

<img width="1141" alt="bildschirmfoto 2016-12-28 um 08 58 33" src="https://cloud.githubusercontent.com/assets/207759/21517060/17e5266e-ccdc-11e6-8fb4-876d39636a90.png">

**Comment by PatrickLang** [comment]
Got PR #527 open. The aka.ms link is live, can you give it a try?

**Comment by StefanScherer** [comment]
Tried it with the https link and it works fine! Thank you.

**Comment by PatrickLang** [comment]
Done. Thanks!
