### ISSUE TITLE
No Gateway attributed when doing inspect container

### ISSUE THREAD

**Issue by eliassal** [Microsoft/Virtualization-Documentation#526]
Hi, I spin a container (docker on win 10, not win for docker), container gets up and running and can access it in the browser using its internal IP. I did a 
Docker inspect mycontainer
I don't see that it has a gateway as you can notice in the details hereunder, is this normal?

Networks": {
   "nat": {
       "IPAMConfig": null,
       "Links": null,
       "Aliases": null,
       "NetworkID": "c5b0f5db8b1686f9aaf654b061dc09d115e2e9c6e3631b14c9e5caef1691cb17",
       "EndpointID": "f953389045b534310cd0223a3142b3fb913a9e7919bfada04c54d0fcce6e1aae",
       "Gateway": "",
       "IPAddress": "172.24.169.145",
       "IPPrefixLen": 16,
       "IPv6Gateway": "",
       "GlobalIPv6Address": "",
       "GlobalIPv6PrefixLen": 0,
       "MacAddress": "00:15:5d:79:12:6f"
   }

Thanks

**Comment by PatrickLang** [comment]
Can you `docker exec ... ipconfig /all` for the container and see if Windows reports a gateway or not? I think this will probably need to be filed at https://www.github.com/docker/docker/issues

**Comment by eliassal** [comment]
Here is the output of 2 machines 
- **Docker inspect details**

>  "Networks": {
>      "nat": {
>          "IPAMConfig": null,
>          "Links": null,
>          "Aliases": null,
>          "NetworkID": "7679f9e17889deda434e7f019e9cc054eea400c24f35d3a45fc692614bbee8d5",
>          "EndpointID": "e0fbb292d3fecffc56f182a7127a9b92272338aee7e95a41e49b635aaddfd543",
>          "Gateway": "",
>          "IPAddress": "172.24.161.2",
>          "IPPrefixLen": 16,
>          "IPv6Gateway": "",
>          "GlobalIPv6Address": "",
>          "GlobalIPv6PrefixLen": 0,
>          "MacAddress": "00:15:5d:79:10:49"
> 

- **ipconfig Details**

   

> Host Name . . . . . . . . . . . . : 163e96c62a1a
>    Primary Dns Suffix  . . . . . . . :
>    Node Type . . . . . . . . . . . . : Hybrid
>    IP Routing Enabled. . . . . . . . : No
>    WINS Proxy Enabled. . . . . . . . : No
> Ethernet adapter Ethernet:
> 
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter
>    Physical Address. . . . . . . . . : 00-15-5D-79-10-49
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::b47a:c65d:7088:7091%4(Preferred)
>    IPv4 Address. . . . . . . . . . . : 172.24.161.2(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.240.0
>    Default Gateway . . . . . . . . . : 172.24.160.1
>    DHCPv6 IAID . . . . . . . . . . . : 67114333
>    DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1F-F7-FC-EF-00-15-5D-79-10-49
>    DNS Servers . . . . . . . . . . . : 172.24.160.1
>                                        192.168.1.13
>    NetBIOS over Tcpip. . . . . . . . : Disabled
> 

Here is the details for the 2nd machine
- **docker inspect details**

 

> "Networks": {
>     "nat": {
>         "IPAMConfig": null,
>         "Links": null,
>         "Aliases": [
>             "f9fefb7986c2",
>             "db"
>         ],
>         "NetworkID": "7679f9e17889deda434e7f019e9cc054eea400c24f35d3a45fc692614bbee8d5",
>         "EndpointID": "db574bbf06f7cb65d5813b4cce1299f2004e3c3fb5529732f07b832b855a47e6",
>         "Gateway": "",
>         "IPAddress": "172.24.161.75",
>         "IPPrefixLen": 16,
>         "IPv6Gateway": "",
>         "GlobalIPv6Address": "",
>         "GlobalIPv6PrefixLen": 0,
>         "MacAddress": "00:15:5d:79:17:73"

- **ipConfig details**
   

> Host Name . . . . . . . . . . . . : f9fefb7986c2
>    Primary Dns Suffix  . . . . . . . :
>    Node Type . . . . . . . . . . . . : Hybrid
>    IP Routing Enabled. . . . . . . . : No
>    WINS Proxy Enabled. . . . . . . . : No
> 
> Ethernet adapter Ethernet 2:
> 
>    Connection-specific DNS Suffix  . :
>    Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #2
>    Physical Address. . . . . . . . . : 00-15-5D-79-17-73
>    DHCP Enabled. . . . . . . . . . . : Yes
>    Autoconfiguration Enabled . . . . : Yes
>    Link-local IPv6 Address . . . . . : fe80::48ef:ee84:292c:ca00%5(Preferred)
>    IPv4 Address. . . . . . . . . . . : 172.24.161.75(Preferred)
>    Subnet Mask . . . . . . . . . . . : 255.255.240.0
>    Default Gateway . . . . . . . . . : 172.24.160.1
>    DHCPv6 IAID . . . . . . . . . . . : 83891549
>    DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1F-F7-FE-70-00-15-5D-79-17-73
>    DNS Servers . . . . . . . . . . . : 172.24.160.1
>                                        192.168.1.13
>    NetBIOS over Tcpip. . . . . . . . : Disabled
>

**Comment by PatrickLang** [comment]
Yeah, that's definitely a Docker bug. Can you file this in https://www.github.com/docker/docker/issues ? I can't find a matching issue there.

Thanks!

**Comment by eliassal** [comment]
Done Patrick
