### ISSUE TITLE
A shorter nodejs image?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/Virtualization-Documentation#54]
Looks like there could be a shorter version of nodejs image compared to what we have in the samples:

```
FROM windowsservercore

ENV NPM_CONFIG_LOGLEVEL info  
ENV IOJS_VERSION 3.2.0

RUN powershell -Command "wget -Uri https://iojs.org/dist/v%IOJS_VERSION%/iojs-v%IOJS_VERSION%-x64.msi -OutFile iojs.msi -UseBasicParsing"

RUN msiexec.exe /q /i iojs.msi

CMD [ "iojs" ] 
```

https://stefanscherer.github.io/create-an-io-js-container-image-for-windows/ @stefanscherer

**Comment by StefanScherer** [comment]
Thanks @ahmetalpbalkan for connecting the dots. This is great to see more and more open source projects so it becomes easier to give feedback.

The example above is for io.js. A more suitable example for Node.js 0.12.7 can be found in this [Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/node/0.12/Dockerfile)

```
FROM windowsservercore

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 0.12.7

RUN powershell -Command "wget -Uri https://nodejs.org/dist/v%NODE_VERSION%/x64/node-v%NODE_VERSION%-x64.msi -OutFile node.msi -UseBasicParsing"

RUN msiexec.exe /q /i node.msi

CMD [ "node" ]
```

And is derived from the official [node](https://hub.docker.com/_/node/) Docker image and its [0.12/Dockerfile](https://github.com/nodejs/docker-node/blob/d798690bdae91174715ac083e31198674f044b68/0.12/Dockerfile).

But there are still some differences. What I haven't tried in a Windows Container is:

* Verify the download with the SHA256 checksum
* Combine multiple shell commands into one RUN command to make it atomic. So you can download file, extract them, install them and remove the downloads and temp files without adding those files into the layer. (Perhaps a Dockerfile should have a feature to make multiple RUN commands atomic...)

I also have assumed that the `RUN msiexec ...` command waits until msiexec is really done. I've seen the extra wait section in the Powershell script.

**Comment by jhowardmsft** [comment]
Correct - run will wait until the process exits. You can probably use `RUN powershell..... && msiexec...` to make it atomic. To avoid long lines, use ` \` as the continuation character at the end of a line. You should also be able to shorten the ENV using the alternate syntax `ENV A=1 B=2`

**Comment by StefanScherer** [comment]
I've played with the SHA256 checksum and atomic commands and came up to this Dockerfile using only one RUN and multiple commands in one powershell script:

```
FROM windowsservercore

ENV NPM_CONFIG_LOGLEVEL info
ENV IOJS_VERSION 3.3.0
ENV IOJS_SHA256 68289641c2780e8c34fc9d4c1c92290d5adb7612b4979722523d6212c79bb0d0

RUN powershell -Command " \
    wget -Uri https://iojs.org/dist/v%IOJS_VERSION%/iojs-v%IOJS_VERSION%-x64.msi -OutFile iojs.msi -UseBasicParsing; \
    if ((Get-FileHash iojs.msi -Algorithm sha256).Hash -ne $env:IOJS_SHA256) {exit 1}; \
    msiexec /q /i iojs.msi | Out-Null; \
    Remove-Item -Path iojs.msi; \
    "

CMD [ "iojs" ]
```

**Comment by neilpeterson** [comment]
I'm assuming that this is no longer an issue, if so, please advise and we can re-open.
