### ISSUE TITLE
Securing Windows Containers - Best Practice?

### ISSUE THREAD

**Issue by pennywisdom** [Microsoft/Virtualization-Documentation#561]
I have been looking around and I am unable to find a good resource on recommended best practice for securing containers. I was wondering if there was any guidance documentation available yet?

There is [docker-security-bench](https://github.com/docker/docker-bench-security) that works well with Linux containers and it would be awesome to eventually have similar vulnerability / best practice checking for windows containers.

A couple of examples for guidance that I am thinking of would include:

1) Security scanning of the built images, finding vulnerabilities, locking down ports (firewall in container? or similar to iptables), other leaks etc.
2) Restricting scripting capabilities for people creating containers in an organisation. So for example, say you limit access to base containers from a known private registry, that are fully patched and scanned (custom or otherwise) and have say Java or similar framework already installed, but then you limit the scripting options that can be run in Dockerfiles building on these base images. How do you guard against the potential to run powershell's invoke-webrequest or similar to get scripts or executables remotely etc in an uncontrolled way. I guess you could do this from a network perspective but that's somewhat unrealistic in a general development network.

Trying to investigate the options outside of Network security that can be applied at the build stage.

Thanks

**Comment by StefanScherer** [comment]
Hi Alex, 
That are really good questions. Maybe we find a way to create a documentation or some tools about security.

A Docker image is a snapshot that you can't modify, only by creating a different image from it or run it as a container and modify files at runtime.
So to be sure to have the unmodified version, just kill the container and run a new one.

What I did in a short test is run a Linux container that modify some files at runtime and check this with `docker diff`

```
$ docker run -it ubuntu bash
root@81084a5373e4:/# touch file1.txt
root@81084a5373e4:/# touch file2.txt
root@81084a5373e4:/# 
```

Now parallel in another terminal run

```
$ docker diff 8108
A /file1.txt
A /file2.txt
```

So you can monitor what has changed at runtime and eg. check if someone has change executables etc.

Similar in a Windows container:

```
$ docker run -it microsoft/windowsservercore cmd

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>echo hello >file1.txt
C:\>echo hello >file2.txt
C:\>
```

Unfortunately this command does not work (yet?) with Windows containers:

```
$ docker diff 5584
Error response from daemon: Windows does not support diff of a running container
```

This might be a use-case for `docker diff` and `docker commit` on Windows. Pinging @taylorb-microsoft any plans to have these commands on Windows?

**Comment by pennywisdom** [comment]
Thanks @StefanScherer. I think these areas need to be considered from an compliance perspective. Its great to have the base images regularly updated and pushed out at regular intervals, but this only goes so far. To have some level of tooling support will provide foundations from which to build on.

**Comment by friism** [comment]
Note that [Docker Hub does security scanning](https://blog.docker.com/2016/05/docker-security-scanning/). You can see example results for a Windows image here: https://hub.docker.com/r/library/golang/tags/1.8-nanoserver/

**Comment by StefanScherer** [comment]
Yes, that's right, I forgot. Notice: You have to be logged in with your Docker Hub account to avoid 404 and see the output of the security scan.

**Comment by pennywisdom** [comment]
Ah this looks good. Unfortunately the values us lost if you will not be using the public docker registry.

**Comment by pennywisdom** [comment]
It does though, give an insight into the kinds of things we will want to be scanning / reviewing. Again though, I'm not sure maintaining such a whitelist of good and bad components / releases is overhead you'd want when using private registries.

**Comment by friism** [comment]
@pennywisdom you can buy for private repositories on Docker Hub/Cloud and it's also available on-prem with Docker Trusted Registry: https://blog.docker.com/2017/02/docker-datacenter-1-13/
