### ISSUE TITLE
Win10 Debug-ContainerHost.ps1 hosts fails when RSAT is installed

### ISSUE THREAD

**Issue by rs38** [Microsoft/Virtualization-Documentation#565]
testing **Has 'Containers' feature installed**
`(Get-Command Get-WindowsFeature -ErrorAction Ignore) -eq $null`
is no longer $null when RSAT is installed on Win10 and the ELSE part does then throw an error as it does not expect a client OS.

**Comment by PatrickLang** [comment]
The original check I had was `(Get-ComputerInfo).OsOperatingSystemSKU -eq "Workstation"`. That quit working in Windows Insider builds and is still broken today. OsOperatingSystemSKU is always null.

The bug #565 was that I was checking for a commandlet that doesn't normally exist on Windows 10, but does with the Remote Server Administration Tools installed.

So this is back to the original method but checking a different property.
