### ISSUE TITLE
create container image gives catastrophic failure

### ISSUE THREAD

**Issue by Ravenlord666** [Microsoft/Virtualization-Documentation#63]
Hi,

I tried making an elasticsearch image like the minecraft example, everything runs well until creating the image:

[Container Host]:: Create image from container
new-containerimage : Failed to define container image.
Failed to create container image.
Failed to define container image.
Failed to create container image: Catastrophic failure (0x8000FFFF).
At C:\Users\stylelabs\Documents\stylelabs.docker\containers\m-elasticsearch\windows\m-elasticsearch.ps1:44 char:2
+     new-containerimage -Container $buildContainer -Publisher $publish ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ContainerImage], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.Containers.PowerShell.Cmdlets.NewContainerImage

I'm running on a Windows server 2016 TP3 hosted on azure.
I also tried it with a fresh VM where I only installed git

**Comment by KarolKaczmarek** [comment]
I'm hitting the same error.
Was following the walkthrough from: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/manage_powershell 

and 
```
$newimage = New-ContainerImage -ContainerName MyContainer -Publisher Demo -Name newimage -Version 1.0
```
throws the error mentioned above

**Comment by scooley** [comment]
I'll try (or find someone to try) to get a repro on Azure.

@enderb-ms @neilpeterson in case either of them know what's up.

Thanks :)

**Comment by jhowardmsft** [comment]
There were several errors like this around TP3 timeframe. It's likely that the ZDP package isn't installed. 3074683.

**Comment by KarolKaczmarek** [comment]
@jhowardmsft  How do I install the ZDP package/where can I find it?

**Comment by jhowardmsft** [comment]
Pretty sure it's https://support.microsoft.com/en-us/kb/3074683

**Comment by scooley** [comment]
@KarolKaczmarek let us know if that works, I'll document it.

**Comment by jhowardmsft** [comment]
It should be picked up automatically by Windows Update too.

**Comment by KarolKaczmarek** [comment]
The second time I tried, it worked fine. Possibly due to Windows Update
