### ISSUE TITLE
Python not working in Docker Container

### ISSUE THREAD

**Issue by hvram1** [Microsoft/Virtualization-Documentation#65]
Tried installing python by copying the C:\Python27 directory and setting the PATH etc. But when I run the command I don't see any output and the command just exits. Is there a better way to run this 

I am using Python 2.7.10 which runs fine on the Windows box

**Comment by pydanny** [comment]
A Docker/Python web app example would be extremely helpful. Preferably Django, but even Flask would help.

**Comment by scooley** [comment]
Couple new samples posted by @enderb-ms [available here](https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-samples).

Let us know if there are other things missing.
