### ISSUE TITLE
Creating virtual switch using ARM Azure VM

### ISSUE THREAD

**Issue by KarolKaczmarek** [Microsoft/Virtualization-Documentation#81]
We need to provide name of the virtual switch when creating a container:
```
$container = New-Container -Name "MyContainer" -ContainerImageName WindowsServerCore -SwitchName "Virtual Switch"
```
When I was creating a classic Azure VM, as in: https://msdn.microsoft.com/virtualization/windowscontainers/quick_start/azure_setup , the virtual switch is created by default
```
PS C:\Program Files\WindowsPowerShell\modules> get-vmswitch

Name           SwitchType NetAdapterInterfaceDescription
----           ---------- ------------------------------
Virtual Switch NAT

```

However, when I'm working on Azure VM created using ARM template, Get-VMSwitch does not return anything... 
How do I add VM switch to the ARM VM?

**Comment by scooley** [comment]
Looking into this :).  Thank you

**Comment by neilpeterson** [comment]
I've deployed the TP4 template using ARM with no issues. The VMSwitch was present, type of NAT, and name of 'Virtual Switch'. I do not think that there is an issue here.

**Comment by KarolKaczmarek** [comment]
Could you paste the template? Or at least name of the image you used to deploy VM?

**Comment by neilpeterson** [comment]
Here you go, feel free to follow up with me if needed.

- Display Name in Azure: '**Windows Server 2016 Core with Containers Tech Preview 4**'.
- Image Name (PowerShell, json, etc.): '**2016-Technical-Preview-with-Containers**'.
- Here is a pre-created template that should work (I updated it last night for TP4) - [2016-Technical-Preview-with-Containers](2016-Technical-Preview-with-Containers).

**Comment by KarolKaczmarek** [comment]
That's what I thought, you are using image which was pre-configured to work with containers (and thus has Virtual Switch present).
I was trying the scenario where clean image is used, in my case:
```
"imagePublisher": "MicrosoftWindowsServer", 
"imageOffer": "WindowsServer", 
"sku":"Windows-Server-Technical-Preview"
```

How do I configure VMSwitch on those so that I can create containers on any image, not only on the one you guys provide?

**Comment by neilpeterson** [comment]
I have not tried to build a container host in Azure, but here are a few things that may help.

- Manual Deployment Docs - [https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment).
- We also have a script that will convert an existing system into a container host, not sure if it will work in Azure [https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/inplace_setup](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/inplace_setup).
- The command to create a VM Swirtch configure with NAT is `New-VMSwitch -Name "Virtual Switch" -SwitchType NAT -NATSubnetAddress 172.16.0.0/12`.

Hope this helps.

neilp
